{
  "hash": "6dab3a7e4839c5d1b18d4e55641416bd",
  "result": {
    "engine": "knitr",
    "markdown": "# Introduction to Statistical Modeling\n\n\n\n---\n\n# Introduction {.unnumbered}\n\n::: {.callout-note icon=false}\n## 💡 Why Does This Matter?\n\nSo far we have described data, estimated population parameters, and tested\nwhether two groups differ. But many real-world health questions go beyond\nsimple comparisons:\n\n- Does body weight *predict* blood pressure?\n- As age *increases*, how does cholesterol *change*?\n- Can we use a patient's BMI to *estimate* their fasting glucose level?\n\nThese questions require us to model the **relationship between two variables**.\n**Statistical modeling** is the process of building a mathematical equation\nthat describes how one variable is related to another — and using that\nequation to understand, explain, and predict outcomes.\n\nIn this chapter we focus on the simplest and most widely used model:\n**simple linear regression**.\n:::\n\n---\n\n# What Is a Statistical Model?\n\nA **statistical model** is a mathematical equation that describes the\nrelationship between:\n\n- An **outcome variable** (also called the *dependent variable*, *response\n  variable*, or $Y$) — the variable we want to explain or predict.\n- One or more **predictor variables** (also called *independent variables*,\n  *explanatory variables*, or $X$) — the variables we use to explain or\n  predict $Y$.\n\nIn this chapter we study **simple linear regression** — one outcome $Y$\nand one predictor $X$, with a straight-line relationship.\n\n---\n\n# Correlation: Measuring the Relationship\n\nBefore building a model, we first ask: *Is there a relationship between\n$X$ and $Y$, and how strong is it?*\n\n## The Scatter Plot\n\nA **scatter plot** displays pairs of values $(x_i, y_i)$ as points on a\ngraph. The pattern of points reveals the **direction** and **strength**\nof the relationship.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\nn <- 80\n\nd1 <- data.frame(x = rnorm(n), y = 0.8*rnorm(n, mean=0) + rnorm(n,sd=0.5),\n                 type = \"Strong positive\")\nd1$y <- d1$x * 0.9 + rnorm(n, sd=0.3)\n\nd2 <- data.frame(x = rnorm(n), y = -0.9*rnorm(n) + rnorm(n,sd=0.3),\n                 type = \"Strong negative\")\nd2$y <- -d2$x * 0.9 + rnorm(n, sd=0.3)\n\nd3 <- data.frame(x = rnorm(n), y = 0.4*rnorm(n) + rnorm(n,sd=0.9),\n                 type = \"Weak positive\")\nd3$y <- d3$x * 0.3 + rnorm(n, sd=0.9)\n\nd4 <- data.frame(x = rnorm(n), y = rnorm(n),\n                 type = \"No relationship\")\n\nall_d <- rbind(d1, d2, d3, d4)\nall_d$type <- factor(all_d$type,\n                     levels = c(\"Strong positive\",\"Strong negative\",\n                                \"Weak positive\",\"No relationship\"))\n\nggplot(all_d, aes(x = x, y = y)) +\n  geom_point(alpha = 0.5, color = \"#2c7bb6\", size = 1.5) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"#d7191c\",\n              linewidth = 1, formula = y ~ x) +\n  facet_wrap(~ type, nrow = 1, scales = \"free\") +\n  theme_minimal(base_size = 12) +\n  theme(axis.text = element_blank(),\n        axis.ticks = element_blank(),\n        axis.title = element_blank(),\n        panel.grid = element_blank(),\n        strip.text = element_text(face = \"bold\", size = 11))\n```\n\n::: {.cell-output-display}\n![Four possible relationships between two variables](chapter06_statistical_modeling_files/figure-pdf/fig-scatter-types-1.pdf){#fig-scatter-types fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n---\n\n## Pearson's Correlation Coefficient ($r$)\n\nThe **Pearson correlation coefficient** $r$ quantifies the **strength**\nand **direction** of the *linear* relationship between two continuous variables.\n\n$$r = \\frac{\\sum_{i=1}^{n}(x_i - \\bar{x})(y_i - \\bar{y})}\n           {\\sqrt{\\sum_{i=1}^{n}(x_i-\\bar{x})^2 \\cdot \\sum_{i=1}^{n}(y_i-\\bar{y})^2}}$$\n\n### Properties of $r$\n\n- $r$ always lies between **−1 and +1**\n- $r = +1$: perfect positive linear relationship\n- $r = -1$: perfect negative linear relationship\n- $r = 0$: no linear relationship\n\n### Interpreting the Magnitude of $r$\n\n\n::: {#tbl-r-interpret .cell tbl-cap='General guidelines for interpreting the correlation coefficient'}\n\n```{.r .cell-code}\nr_tab <- data.frame(\n  `|r| range` = c(\"0.00 – 0.19\", \"0.20 – 0.39\",\n                   \"0.40 – 0.59\", \"0.60 – 0.79\", \"0.80 – 1.00\"),\n  Strength = c(\"Negligible\", \"Weak\", \"Moderate\", \"Strong\", \"Very strong\"),\n  Direction = c(\"—\", \"Positive or negative depending on sign\",\n                \"Positive or negative depending on sign\",\n                \"Positive or negative depending on sign\",\n                \"Positive or negative depending on sign\")\n)\n\nkable(r_tab, col.names = c(\"|r| value\", \"Strength\", \"Note\"),\n      align = c(\"c\",\"l\",\"l\")) |>\n  kable_styling(bootstrap_options = c(\"striped\",\"hover\",\"bordered\"),\n                full_width = FALSE, font_size = 13) |>\n  column_spec(1, bold = TRUE, color = \"#2c7bb6\")\n```\n\n::: {.cell-output-display}\n\\begingroup\\fontsize{13}{15}\\selectfont\n\n\\begin{longtable}[t]{>{}cll}\n\\toprule\n\\&\\#124;r\\&\\#124; value & Strength & Note\\\\\n\\midrule\n\\textcolor[HTML]{2c7bb6}{\\textbf{0.00 – 0.19}} & Negligible & —\\\\\n\\textcolor[HTML]{2c7bb6}{\\textbf{0.20 – 0.39}} & Weak & Positive or negative depending on sign\\\\\n\\textcolor[HTML]{2c7bb6}{\\textbf{0.40 – 0.59}} & Moderate & Positive or negative depending on sign\\\\\n\\textcolor[HTML]{2c7bb6}{\\textbf{0.60 – 0.79}} & Strong & Positive or negative depending on sign\\\\\n\\textcolor[HTML]{2c7bb6}{\\textbf{0.80 – 1.00}} & Very strong & Positive or negative depending on sign\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n::: {.callout-warning icon=false}\n## ⚠️ Correlation Is Not Causation\n\nA high correlation between $X$ and $Y$ does **not** mean that $X$\n*causes* $Y$. Both variables may be influenced by a third variable,\nor the relationship may be coincidental. Always interpret correlations\nin the context of biological or clinical plausibility.\n:::\n\n---\n\n# Simple Linear Regression\n\n## The Regression Equation\n\nSimple linear regression models the relationship between $X$ and $Y$\nas a straight line:\n\n$$\\hat{Y} = b_0 + b_1 X$$\n\nWhere:\n\n| Symbol | Name | Meaning |\n|:---:|---|---|\n| $\\hat{Y}$ | Predicted value | The estimated value of $Y$ for a given $X$ |\n| $b_0$ | Intercept | The predicted value of $Y$ when $X = 0$ |\n| $b_1$ | Slope | The change in $\\hat{Y}$ for each one-unit increase in $X$ |\n\nThe full model including random error is:\n\n$$Y = b_0 + b_1 X + \\varepsilon$$\n\nWhere $\\varepsilon$ represents the **residual** — the difference between\nthe observed value and the predicted value:\n\n$$\\varepsilon_i = Y_i - \\hat{Y}_i$$\n\n---\n\n## Estimating the Coefficients\n\nThe values of $b_0$ and $b_1$ are chosen to minimize the **sum of squared\nresiduals** — this method is called **Ordinary Least Squares (OLS)**:\n\n$$\\text{Minimize: } \\sum_{i=1}^{n}(Y_i - \\hat{Y}_i)^2 = \\sum_{i=1}^{n}\\varepsilon_i^2$$\n\nThe OLS formulas are:\n\n$$b_1 = \\frac{\\sum_{i=1}^{n}(x_i - \\bar{x})(y_i - \\bar{y})}\n             {\\sum_{i=1}^{n}(x_i - \\bar{x})^2}\n       = r \\cdot \\frac{s_y}{s_x}$$\n\n$$b_0 = \\bar{y} - b_1 \\bar{x}$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(10)\nx <- seq(20, 80, length = 20)\ny <- 60 + 0.9 * x + rnorm(20, sd = 10)\nfit <- lm(y ~ x)\ndf_ols <- data.frame(x = x, y = y,\n                     yhat = fitted(fit),\n                     resid = residuals(fit))\n\nggplot(df_ols, aes(x = x, y = y)) +\n  geom_segment(aes(xend = x, yend = yhat),\n               color = \"#d7191c\", linewidth = 0.7, linetype = \"dashed\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"#2c7bb6\",\n              linewidth = 1.3, formula = y ~ x) +\n  geom_point(size = 3, color = \"#2c7bb6\", alpha = 0.8) +\n  labs(x = \"X (Predictor)\", y = \"Y (Outcome)\",\n       caption = \"Red dashed lines = residuals (ε = Y − Ŷ)\") +\n  theme_minimal(base_size = 13) +\n  theme(panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![Least squares regression line minimizes the sum of squared residuals (vertical red lines)](chapter06_statistical_modeling_files/figure-pdf/fig-ols-1.pdf){#fig-ols fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n---\n\n## The Coefficient of Determination ($R^2$)\n\n**$R^2$** (R-squared) measures how well the regression line fits the data —\nspecifically, the **proportion of the total variation in $Y$ that is\nexplained by $X$**:\n\n$$R^2 = r^2 \\quad \\text{(in simple linear regression)}$$\n\n$$R^2 = \\frac{\\text{Variation explained by the model}}{\\text{Total variation in } Y}$$\n\n- $R^2 = 1$: the model explains 100% of the variation in $Y$ (perfect fit)\n- $R^2 = 0$: the model explains none of the variation in $Y$\n- $R^2 = 0.65$ means: *\"65% of the variation in $Y$ is explained by $X$\"*\n\n---\n\n## Testing the Significance of the Regression\n\nBefore using the regression equation for interpretation or prediction,\nwe should test whether the slope $b_1$ is significantly different from zero.\nIf $b_1 = 0$, then $X$ provides no information about $Y$.\n\n**Hypotheses:**\n\n$$H_0: \\beta_1 = 0 \\quad \\text{(X is not a useful predictor of Y)}$$\n$$H_1: \\beta_1 \\neq 0 \\quad \\text{(X is a useful predictor of Y)}$$\n\nThe test statistic is:\n\n$$t = \\frac{b_1}{SE_{b_1}}$$\n\nwhich follows a t-distribution with $df = n - 2$.\n\nSPSS reports this p-value automatically in the **Coefficients table**\nof the regression output.\n\n---\n\n## Assumptions of Linear Regression\n\nThe regression model is valid only when the following assumptions are met:\n\n\n::: {#tbl-assumptions .cell tbl-cap='Assumptions of Simple Linear Regression'}\n\n```{.r .cell-code}\nassump <- data.frame(\n  Assumption = c(\"Linearity\",\n                 \"Independence\",\n                 \"Homoscedasticity\",\n                 \"Normality of residuals\"),\n  Meaning = c(\n    \"The relationship between X and Y is linear (a straight line is appropriate)\",\n    \"Observations are independent of each other\",\n    \"The spread of residuals is roughly constant across all values of X\",\n    \"Residuals are approximately normally distributed\"\n  ),\n  `How to Check` = c(\n    \"Scatter plot of X vs. Y; residual plot\",\n    \"Study design — satisfied by random sampling\",\n    \"Plot of residuals vs. fitted values — no funnel shape\",\n    \"Histogram or Q-Q plot of residuals\"\n  )\n)\n\nkable(assump, col.names = c(\"Assumption\", \"Meaning\", \"How to Check\"),\n      align = c(\"l\",\"l\",\"l\")) |>\n  kable_styling(bootstrap_options = c(\"striped\",\"hover\",\"bordered\"),\n                full_width = TRUE, font_size = 13) |>\n  column_spec(1, bold = TRUE, color = \"#2c7bb6\")\n```\n\n::: {.cell-output-display}\n\\begingroup\\fontsize{13}{15}\\selectfont\n\n\\begin{longtabu} to \\linewidth {>{}l>{\\raggedright}X>{\\raggedright}X}\n\\toprule\nAssumption & Meaning & How to Check\\\\\n\\midrule\n\\textcolor[HTML]{2c7bb6}{\\textbf{Linearity}} & The relationship between X and Y is linear (a straight line is appropriate) & Scatter plot of X vs. Y; residual plot\\\\\n\\textcolor[HTML]{2c7bb6}{\\textbf{Independence}} & Observations are independent of each other & Study design — satisfied by random sampling\\\\\n\\textcolor[HTML]{2c7bb6}{\\textbf{Homoscedasticity}} & The spread of residuals is roughly constant across all values of X & Plot of residuals vs. fitted values — no funnel shape\\\\\n\\textcolor[HTML]{2c7bb6}{\\textbf{Normality of residuals}} & Residuals are approximately normally distributed & Histogram or Q-Q plot of residuals\\\\\n\\bottomrule\n\\end{longtabu}\n\\endgroup{}\n\n\n:::\n:::\n\n\n---\n\n## Reading SPSS Regression Output\n\nSPSS produces three key tables for simple linear regression.\nHere is how to read them:\n\n\n::: {#tbl-spss-model .cell tbl-cap='SPSS Output: Model Summary'}\n\n```{.r .cell-code}\nmodel_sum <- data.frame(\n  R = \"0.821\",\n  R2 = \"0.674\",\n  `Adjusted R²` = \"0.666\",\n  `Std. Error of the Estimate` = \"8.432\"\n)\n\nkable(model_sum,\n      col.names = c(\"R\", \"R²\", \"Adjusted R²\", \"Std. Error of the Estimate\"),\n      align = rep(\"c\",4)) |>\n  kable_styling(bootstrap_options = c(\"bordered\"),\n                full_width = FALSE, font_size = 13) |>\n  row_spec(0, bold = TRUE, color = \"white\", background = \"#2c7bb6\")\n```\n\n::: {.cell-output-display}\n\\begingroup\\fontsize{13}{15}\\selectfont\n\n\\begin{longtable}[t]{cccc}\n\\toprule\n\\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{R}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{R²}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{Adjusted R²}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{Std. Error of the Estimate}}}\\\\\n\\midrule\n0.821 & 0.674 & 0.666 & 8.432\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n→ **R = 0.821** (strong positive correlation); **R² = 0.674** (67.4% of\nvariation in Y explained by X).\n\n\n::: {#tbl-spss-anova .cell tbl-cap='SPSS Output: ANOVA Table'}\n\n```{.r .cell-code}\nanova_tab <- data.frame(\n  Source = c(\"Regression\", \"Residual\", \"Total\"),\n  SS = c(\"5621.4\", \"2718.6\", \"8340.0\"),\n  df = c(\"1\", \"38\", \"39\"),\n  MS = c(\"5621.4\", \"71.5\", \"\"),\n  F = c(\"78.62\", \"\", \"\"),\n  Sig = c(\"< 0.001\", \"\", \"\")\n)\n\nkable(anova_tab,\n      col.names = c(\"\", \"Sum of Squares\", \"df\", \"Mean Square\", \"F\", \"Sig.\"),\n      align = c(\"l\",\"c\",\"c\",\"c\",\"c\",\"c\")) |>\n  kable_styling(bootstrap_options = c(\"bordered\"),\n                full_width = FALSE, font_size = 13) |>\n  row_spec(0, bold = TRUE, color = \"white\", background = \"#2c7bb6\") |>\n  row_spec(1, bold = TRUE)\n```\n\n::: {.cell-output-display}\n\\begingroup\\fontsize{13}{15}\\selectfont\n\n\\begin{longtable}[t]{lccccc}\n\\toprule\n\\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{Sum of Squares}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{df}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{Mean Square}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{F}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{Sig.}}}\\\\\n\\midrule\n\\textbf{Regression} & \\textbf{5621.4} & \\textbf{1} & \\textbf{5621.4} & \\textbf{78.62} & \\textbf{< 0.001}\\\\\nResidual & 2718.6 & 38 & 71.5 &  & \\\\\nTotal & 8340.0 & 39 &  &  & \\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n→ **F = 78.62, p < 0.001** — the overall regression model is\nstatistically significant.\n\n\n::: {#tbl-spss-coef .cell tbl-cap='SPSS Output: Coefficients Table'}\n\n```{.r .cell-code}\ncoef_tab <- data.frame(\n  ` ` = c(\"(Constant)\", \"X (predictor)\"),\n  B = c(\"32.15\", \"0.87\"),\n  SE = c(\"6.24\", \"0.10\"),\n  Beta = c(\"—\", \"0.821\"),\n  t = c(\"5.15\", \"8.87\"),\n  Sig = c(\"< 0.001\", \"< 0.001\")\n)\n\nkable(coef_tab,\n      col.names = c(\"\", \"B\", \"Std. Error\", \"Beta (standardized)\", \"t\", \"Sig.\"),\n      align = c(\"l\",\"c\",\"c\",\"c\",\"c\",\"c\")) |>\n  kable_styling(bootstrap_options = c(\"bordered\"),\n                full_width = FALSE, font_size = 13) |>\n  row_spec(0, bold = TRUE, color = \"white\", background = \"#2c7bb6\") |>\n  row_spec(2, bold = TRUE, background = \"#eaf4fb\")\n```\n\n::: {.cell-output-display}\n\\begingroup\\fontsize{13}{15}\\selectfont\n\n\\begin{longtable}[t]{lccccc}\n\\toprule\n\\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{B}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{Std. Error}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{Beta (standardized)}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{t}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{Sig.}}}\\\\\n\\midrule\n(Constant) & 32.15 & 6.24 & — & 5.15 & < 0.001\\\\\n\\cellcolor[HTML]{eaf4fb}{\\textbf{X (predictor)}} & \\cellcolor[HTML]{eaf4fb}{\\textbf{0.87}} & \\cellcolor[HTML]{eaf4fb}{\\textbf{0.10}} & \\cellcolor[HTML]{eaf4fb}{\\textbf{0.821}} & \\cellcolor[HTML]{eaf4fb}{\\textbf{8.87}} & \\cellcolor[HTML]{eaf4fb}{\\textbf{< 0.001}}\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n→ **Regression equation:** $\\hat{Y} = 32.15 + 0.87X$\n\n→ The slope **B = 0.87** is statistically significant ($p < 0.001$):\nfor each one-unit increase in $X$, $Y$ increases by **0.87 units** on average.\n\n---\n\n# Key Takeaways\n\n::: {.callout-note icon=false}\n## 📝 Chapter 6 Summary\n\n1. **Statistical modeling** describes the mathematical relationship between\n   an outcome variable $Y$ and one or more predictor variables $X$.\n\n2. **Pearson's $r$** measures the strength and direction of a linear\n   relationship between two continuous variables ($-1 \\leq r \\leq +1$).\n\n3. **Simple linear regression** fits the equation $\\hat{Y} = b_0 + b_1 X$\n   using the least squares method, which minimizes the sum of squared residuals.\n\n4. The **slope $b_1$** tells us how much $Y$ changes for each one-unit\n   increase in $X$; the **intercept $b_0$** is the predicted value of $Y$\n   when $X = 0$.\n\n5. **$R^2$** is the proportion of variation in $Y$ explained by the model.\n   A higher $R^2$ means a better fit.\n\n6. Always test whether $b_1$ is significantly different from zero ($H_0: \\beta_1 = 0$)\n   before using the model for interpretation.\n\n7. The model is only valid when the four assumptions — **linearity,\n   independence, homoscedasticity, and normality of residuals** — are\n   reasonably satisfied.\n:::\n\n---\n\n# Examples\n\n## Example 1: Calculating Correlation and Regression\n\nA researcher records the **age (years)** and **systolic blood pressure (mmHg)**\nof 8 adults:\n\n\n::: {#tbl-ex1-data .cell tbl-cap='Age and Systolic Blood Pressure of 8 Adults'}\n\n```{.r .cell-code}\nage <- c(25, 32, 40, 48, 55, 62, 70, 78)\nsbp <- c(115, 120, 128, 135, 142, 148, 158, 165)\n\nex1 <- data.frame(Subject = paste0(\"S\", 1:8), Age = age, SBP = sbp)\n\nkable(ex1, col.names = c(\"Subject\", \"Age (years)\", \"SBP (mmHg)\"),\n      align = c(\"c\",\"c\",\"c\")) |>\n  kable_styling(bootstrap_options = c(\"striped\",\"hover\",\"bordered\"),\n                full_width = FALSE, font_size = 13)\n```\n\n::: {.cell-output-display}\n\\begingroup\\fontsize{13}{15}\\selectfont\n\n\\begin{longtable}[t]{ccc}\n\\toprule\nSubject & Age (years) & SBP (mmHg)\\\\\n\\midrule\nS1 & 25 & 115\\\\\nS2 & 32 & 120\\\\\nS3 & 40 & 128\\\\\nS4 & 48 & 135\\\\\nS5 & 55 & 142\\\\\n\\addlinespace\nS6 & 62 & 148\\\\\nS7 & 70 & 158\\\\\nS8 & 78 & 165\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n**(a)** Calculate Pearson's $r$.\n\n**(b)** Find the regression equation $\\hat{Y} = b_0 + b_1 X$.\n\n**(c)** Predict the SBP of a 50-year-old adult.\n\n**(d)** Interpret $R^2$.\n\n::: {.callout-tip icon=false}\n## ✅ Solution\n\n\n::: {#tbl-ex1-calc .cell tbl-cap='Calculation Table for Correlation and Regression'}\n\n```{.r .cell-code}\nxbar <- mean(age)\nybar <- mean(sbp)\n\ncalc <- data.frame(\n  Subject = paste0(\"S\", 1:8),\n  x = age,\n  y = sbp,\n  xdev = round(age - xbar, 2),\n  ydev = round(sbp - ybar, 2),\n  xdev2 = round((age - xbar)^2, 2),\n  ydev2 = round((sbp - ybar)^2, 2),\n  xydev = round((age - xbar)*(sbp - ybar), 2)\n)\n\ntotrow <- data.frame(\n  Subject = \"**Total**\",\n  x = NA, y = NA,\n  xdev = NA, ydev = NA,\n  xdev2 = round(sum((age-xbar)^2), 2),\n  ydev2 = round(sum((sbp-ybar)^2), 2),\n  xydev = round(sum((age-xbar)*(sbp-ybar)), 2)\n)\n\ncalc_all <- rbind(calc, totrow)\n\nkable(calc_all,\n      col.names = c(\"Subject\",\"x\",\"y\",\"x−x̄\",\"y−ȳ\",\n                    \"(x−x̄)²\",\"(y−ȳ)²\",\"(x−x̄)(y−ȳ)\"),\n      align = rep(\"c\", 8), escape = FALSE, na_print = \"—\") |>\n  kable_styling(bootstrap_options = c(\"striped\",\"hover\",\"bordered\"),\n                full_width = TRUE, font_size = 12) |>\n  row_spec(9, bold = TRUE, background = \"#eaf4fb\") |>\n  row_spec(0, bold = TRUE, color = \"white\", background = \"#2c7bb6\")\n```\n\n::: {.cell-output-display}\n\\begingroup\\fontsize{12}{14}\\selectfont\n\n\\begin{longtabu} to \\linewidth {>{\\centering}X>{\\centering}X>{\\centering}X>{\\centering}X>{\\centering}X>{\\centering}X>{\\centering}X>{\\centering}X}\n\\toprule\n\\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{Subject}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{x}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{y}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{x−x̄}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{|  y−ȳ}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{| (x−x̄)²}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{| (y−ȳ)²}}} & \\cellcolor[HTML]{2c7bb6}{\\textcolor{white}{\\textbf{| (x−x̄)(y−}}}\\\\\n\\midrule\nS1 & 25 & 115 & -26.25 & -23.88 & 689.06 & 570.02 & 626.72\\\\\nS2 & 32 & 120 & -19.25 & -18.88 & 370.56 & 356.27 & 363.34\\\\\nS3 & 40 & 128 & -11.25 & -10.88 & 126.56 & 118.27 & 122.34\\\\\nS4 & 48 & 135 & -3.25 & -3.88 & 10.56 & 15.02 & 12.59\\\\\nS5 & 55 & 142 & 3.75 & 3.12 & 14.06 & 9.77 & 11.72\\\\\n\\addlinespace\nS6 & 62 & 148 & 10.75 & 9.12 & 115.56 & 83.27 & 98.09\\\\\nS7 & 70 & 158 & 18.75 & 19.12 & 351.56 & 365.77 & 358.59\\\\\nS8 & 78 & 165 & 26.75 & 26.12 & 715.56 & 682.52 & 698.84\\\\\n\\cellcolor[HTML]{eaf4fb}{\\textbf{**Total**}} & \\cellcolor[HTML]{eaf4fb}{\\textbf{NA}} & \\cellcolor[HTML]{eaf4fb}{\\textbf{NA}} & \\cellcolor[HTML]{eaf4fb}{\\textbf{NA}} & \\cellcolor[HTML]{eaf4fb}{\\textbf{NA}} & \\cellcolor[HTML]{eaf4fb}{\\textbf{2393.50}} & \\cellcolor[HTML]{eaf4fb}{\\textbf{2200.88}} & \\cellcolor[HTML]{eaf4fb}{\\textbf{2292.25}}\\\\\n\\bottomrule\n\\end{longtabu}\n\\endgroup{}\n\n\n:::\n:::\n\n\n**(a) Pearson's r:**\n\n$$r = \\frac{\\sum(x_i-\\bar{x})(y_i-\\bar{y})}\n           {\\sqrt{\\sum(x_i-\\bar{x})^2 \\cdot \\sum(y_i-\\bar{y})^2}}\n  = \\frac{2292.25}\n         {\\sqrt{2393.5 \\times 2200.88}}\n  = \\frac{2292.25}\n         {2295.17}\n  = \\mathbf{0.999}$$\n\nThis indicates a **very strong positive** linear relationship between\nage and systolic blood pressure.\n\n**(b) Regression coefficients:**\n\n$$b_1 = \\frac{\\sum(x_i-\\bar{x})(y_i-\\bar{y})}{\\sum(x_i-\\bar{x})^2}\n      = \\frac{2292.25}\n             {2393.5}\n      = 0.958$$\n\n$$b_0 = \\bar{y} - b_1\\bar{x}\n      = 138.88 - 0.958 \\times 51.25\n      = 89.79$$\n\n$$\\boxed{\\hat{Y} = 89.79 + 0.958 X}$$\n\n**(c) Prediction for age = 50:**\n\n$$\\hat{Y} = 89.79 + 0.958 \\times 50\n          = 137.7 \\text{ mmHg}$$\n\n**(d) $R^2$:**\n\n$$R^2 = r^2 = (0.999)^2 = 0.997$$\n\n**99.7% of the variation in systolic blood pressure\nis explained by age.** The remaining 0.3%\nis due to other factors not included in this model.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit1 <- lm(sbp ~ age)\ndf1  <- data.frame(age = age, sbp = sbp)\n\nggplot(df1, aes(x = age, y = sbp)) +\n  geom_point(size = 3.5, color = \"#2c7bb6\") +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"#d7191c\",\n              fill = \"#fdae61\", alpha = 0.2, formula = y ~ x) +\n  annotate(\"text\", x = 30, y = 162,\n           label = paste0(\"Ŷ = \", round(coef(fit1)[1],2),\n                          \" + \", round(coef(fit1)[2],3), \"X\\n\",\n                          \"r = \", round(cor(age,sbp),3),\n                          \",  R² = \", round(cor(age,sbp)^2,3)),\n           hjust = 0, size = 4, color = \"#d7191c\") +\n  labs(x = \"Age (years)\", y = \"Systolic Blood Pressure (mmHg)\") +\n  theme_minimal(base_size = 13) +\n  theme(panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![Scatter plot with fitted regression line: Age vs. Systolic Blood Pressure](chapter06_statistical_modeling_files/figure-pdf/fig-ex1-fit-1.pdf){#fig-ex1-fit fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n---\n\n## Example 2: Interpreting SPSS Output\n\nA researcher uses SPSS to examine the relationship between\n**BMI (kg/m²)** and **fasting blood glucose (mg/dL)** in 60 adults.\nThe following output is obtained:\n\n**Model Summary:**\n\n| R | R² | Adjusted R² | Std. Error |\n|:---:|:---:|:---:|:---:|\n| 0.612 | 0.375 | 0.364 | 14.23 |\n\n**Coefficients:**\n\n| | B | Std. Error | t | Sig. |\n|---|:---:|:---:|:---:|:---:|\n| (Constant) | 48.32 | 11.45 | 4.22 | < 0.001 |\n| BMI | 2.91 | 0.46 | 6.33 | < 0.001 |\n\n::: {.callout-tip icon=false}\n## ✅ Interpretation\n\n**Correlation:** $r = 0.612$ — a **moderate-to-strong positive**\nrelationship between BMI and fasting blood glucose.\n\n**Regression equation:**\n$$\\hat{Y} = 48.32 + 2.91 \\times \\text{BMI}$$\n\n**Slope ($b_1 = 2.91$):** For each 1 kg/m² increase in BMI,\nfasting blood glucose increases by **2.91 mg/dL** on average,\nholding other factors constant.\n\n**Intercept ($b_0 = 48.32$):** The predicted fasting glucose when\nBMI = 0 is 48.32 mg/dL. *(Note: BMI of 0 is not a meaningful value\nin practice — the intercept is simply a mathematical anchor for the line.)*\n\n**$R^2 = 0.375$:** BMI explains **37.5%** of the variation in fasting\nblood glucose. The remaining 62.5% is due to other factors (diet, genetics,\nphysical activity, etc.).\n\n**Significance ($p < 0.001$):** The slope is highly significant —\nBMI is a statistically significant predictor of fasting blood glucose.\n\n**Prediction example:** A person with BMI = 28 kg/m²:\n$$\\hat{Y} = 48.32 + 2.91 \\times 28 = 48.32 + 81.48 = 129.8 \\text{ mg/dL}$$\n:::\n\n---\n\n# Exercises\n\n::: {.callout-caution icon=false}\n## ✏️ Exercise 1\n\nA study records the **hours of sleep per night** ($X$) and\n**systolic blood pressure (mmHg)** ($Y$) for 6 adults:\n\n| Subject | Sleep (hrs) | SBP (mmHg) |\n|:---:|:---:|:---:|\n| 1 | 5 | 145 |\n| 2 | 6 | 138 |\n| 3 | 7 | 130 |\n| 4 | 7 | 125 |\n| 5 | 8 | 120 |\n| 6 | 9 | 115 |\n\n**(a)** Draw a scatter plot and describe the relationship.\n\n**(b)** Calculate Pearson's $r$. What does it indicate?\n\n**(c)** Find the regression equation $\\hat{Y} = b_0 + b_1 X$.\n\n**(d)** Predict the SBP of a person who sleeps 6.5 hours per night.\n\n**(e)** Calculate $R^2$ and interpret it.\n:::\n\n::: {.callout-caution icon=false}\n## ✏️ Exercise 2\n\nA researcher uses SPSS to study the relationship between a patient's\n**age (years)** and **total cholesterol (mg/dL)**.\nThe SPSS output gives the following results:\n\n**Model Summary:** R = 0.548, R² = 0.300\n\n**Coefficients:**\n\n| | B | Std. Error | t | Sig. |\n|---|:---:|:---:|:---:|:---:|\n| (Constant) | 120.4 | 18.6 | 6.47 | < 0.001 |\n| Age | 1.85 | 0.31 | 5.97 | < 0.001 |\n\n**(a)** Write the regression equation.\n\n**(b)** Interpret the slope in the context of this study.\n\n**(c)** What proportion of the variation in cholesterol is explained\nby age? Is this a strong model?\n\n**(d)** Predict the total cholesterol of a 55-year-old patient.\n\n**(e)** Is the predictor (age) statistically significant at $\\alpha = 0.05$?\nHow do you know?\n:::\n\n::: {.callout-caution icon=false}\n## ✏️ Exercise 3 — Reflection Questions\n\nAnswer the following in 2–3 sentences each:\n\n**(a)** A researcher finds that the correlation between ice cream sales\nand drowning deaths is $r = 0.85$. Does this mean eating ice cream\ncauses drowning? Explain using the concept of correlation vs. causation.\n\n**(b)** In a regression model predicting patient recovery time from\nage ($R^2 = 0.22$), a colleague says *\"this model is useless because\nit only explains 22% of the variation.\"* Do you agree? What additional\ninformation would help evaluate this claim?\n\n**(c)** Why is it generally not appropriate to use a regression equation\nto predict $Y$ for values of $X$ that are far outside the range of the\noriginal data?\n:::\n\n---\n\n*End of Chapter 6*\n\n---\n\n::: {.callout-note icon=false}\n## 🎓 End of Course\n\nCongratulations on completing all six chapters of Introduction to Biostatistics!\n\nYou have covered the full journey from understanding what data is,\nto summarizing it, to understanding distributions, making estimates,\ntesting hypotheses, and finally modeling relationships between variables.\n\nThese tools form the foundation of evidence-based practice in health science.\n:::\n",
    "supporting": [
      "chapter06_statistical_modeling_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}