<!DOCTYPE html>
<html lang="en"><head>
<script src="ch05_files/libs/clipboard/clipboard.min.js"></script>
<script src="ch05_files/libs/quarto-html/tabby.min.js"></script>
<script src="ch05_files/libs/quarto-html/popper.min.js"></script>
<script src="ch05_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="ch05_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ch05_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="ch05_files/libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.19">

  <meta name="author" content="Asst. Prof.&nbsp;Dr.&nbsp;Parichart Pattarapanitchai">
  <title>Statistical Testing</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="ch05_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="ch05_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="ch05_files/libs/revealjs/dist/theme/quarto-ae7e42f4f0a9bc7cad33dd64a10b9b31.css">
  <link href="ch05_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="ch05_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="ch05_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="ch05_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="ch05_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="ch05_files/libs/revealjs/plugin/reveal-pointer/pointer.css" rel="stylesheet">
  <link href="ch05_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="ch05_files/libs/kePrint-0.0.1/kePrint.js"></script>
  <link href="ch05_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Statistical Testing</h1>
  <p class="subtitle">Chapter 5 | 208141 Introduction to Biostatistics</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Asst. Prof.&nbsp;Dr.&nbsp;Parichart Pattarapanitchai
</div>
</div>
</div>

</section>
<section id="introduction" class="slide level2 unnumbered">
<h2>Introduction</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why Does This Matter?</strong></p>
</div>
<div class="callout-content">
<p>In health research, we constantly ask questions that require a decision:</p>
<ul>
<li>Does this new drug lower blood pressure <em>more</em> than the standard treatment?</li>
<li>Is there a relationship between smoking and lung disease?</li>
<li>Do recovery times differ between two surgical techniques?</li>
</ul>
<p>We cannot answer these questions simply by looking at sample means or proportions — random chance alone can create apparent differences between groups. <strong>Statistical testing</strong> gives us a formal, objective framework for deciding whether an observed difference is likely to be real or simply due to chance.</p>
<p>This is the most widely used tool in health research, and understanding it is essential for reading and interpreting scientific literature.</p>
</div>
</div>
</div>
</section>
<section>
<section id="concept-of-hypothesis-testing" class="title-slide slide level1 center">
<h1>Concept of Hypothesis Testing</h1>

</section>
<section id="the-logic-of-hypothesis-testing" class="slide level2">
<h2>The Logic of Hypothesis Testing</h2>
<p>Statistical testing works by assuming the opposite of what we want to prove, then asking: <em>“If nothing were really happening, how surprising would our data be?”</em></p>
<p>If the data would be very surprising under the assumption that nothing is happening, we conclude that something probably <em>is</em> happening.</p>
</section>
<section id="the-two-hypotheses" class="slide level2">
<h2>The Two Hypotheses</h2>
<p>Every hypothesis test involves two competing statements:</p>
<h3 id="null-hypothesis-h_0">Null Hypothesis (<span class="math inline">\(H_0\)</span>)</h3>
<p>The <strong>null hypothesis</strong> states that there is <strong>no effect, no difference, or no relationship</strong> in the population. It is the assumption we start with and attempt to disprove.</p>
<blockquote>
<p><em>Examples:</em> - The mean blood pressure is 120 mmHg. (<span class="math inline">\(H_0: \mu = 120\)</span>) - There is no difference in recovery time between the two groups. (<span class="math inline">\(H_0: \mu_1 = \mu_2\)</span>) - There is no association between smoking status and disease. (<span class="math inline">\(H_0:\)</span> no association)</p>
</blockquote>
<h3 id="alternative-hypothesis-h_1-or-h_a">Alternative Hypothesis (<span class="math inline">\(H_1\)</span> or <span class="math inline">\(H_a\)</span>)</h3>
<p>The <strong>alternative hypothesis</strong> states that there <strong>is</strong> an effect, difference, or relationship. This is usually what the researcher believes or wants to demonstrate.</p>
<blockquote>
<p><em>Examples:</em> - The mean blood pressure is not 120 mmHg. (<span class="math inline">\(H_1: \mu \neq 120\)</span>) - Recovery time differs between the two groups. (<span class="math inline">\(H_1: \mu_1 \neq \mu_2\)</span>) - There is an association between smoking and disease. (<span class="math inline">\(H_1:\)</span> association exists)</p>
</blockquote>
</section>
<section id="one-tailed-vs.-two-tailed-tests" class="slide level2">
<h2>One-Tailed vs.&nbsp;Two-Tailed Tests</h2>
<p>The alternative hypothesis can be <strong>directional</strong> or <strong>non-directional</strong>:</p>
<div class="cell">
<div id="tbl-tails" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tails-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: One-tailed vs.&nbsp;Two-tailed Tests
</figcaption>
<div aria-describedby="tbl-tails-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-bordered cell caption-top" style="font-size: 13px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Test Type</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">H1</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Use When</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; color: rgba(44, 123, 182, 1) !important; background-color: rgba(234, 244, 251, 1) !important;">Two-tailed</td>
<td style="text-align: left; background-color: rgba(234, 244, 251, 1) !important;">mu != mu0 (different from)</td>
<td style="text-align: left; background-color: rgba(234, 244, 251, 1) !important;">Either direction (most common)</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">One-tailed (right)</td>
<td style="text-align: left;">mu &gt; mu0 (greater than)</td>
<td style="text-align: left;">Only an increase is of interest</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">One-tailed (left)</td>
<td style="text-align: left;">mu &lt; mu0 (less than)</td>
<td style="text-align: left;">Only a decrease is of interest</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Practical Advice</strong></p>
</div>
<div class="callout-content">
<p>In most health research, use a <strong>two-tailed test</strong> unless you have a strong, pre-specified reason to test in only one direction. Two-tailed tests are more conservative and more widely accepted. SPSS reports two-tailed p-values (“Sig. (2-tailed)”), and <strong>all tests in this course are two-tailed</strong>.</p>
<p>After a significant two-tailed test, we still say <strong>which direction</strong> the difference goes by looking at the sample means (or mean ranks).</p>
</div>
</div>
</div>
</section>
<section id="the-test-statistic" class="slide level2">
<h2>The Test Statistic</h2>
<p>A <strong>test statistic</strong> is a single number calculated from the sample that measures <strong>how far the data are from what <span class="math inline">\(H_0\)</span> predicts</strong>. For the t-tests it has the same form as the Z-score in Chapter 3:</p>
<p><span class="math display">\[\text{test statistic} = \frac{\text{what we observed} - \text{what } H_0 \text{ predicts}}{\text{standard error}}\]</span></p>
<ul>
<li>A test statistic <strong>close to 0</strong> means the data agree with <span class="math inline">\(H_0\)</span>.</li>
<li>A test statistic <strong>far from 0</strong> means the data are surprising if <span class="math inline">\(H_0\)</span> is true.</li>
</ul>
<p>Each test in this chapter has its own test statistic (<span class="math inline">\(t\)</span>, <span class="math inline">\(\chi^2\)</span>, <span class="math inline">\(U\)</span>, <span class="math inline">\(W\)</span>) and its own formula, but the idea is the same: the further the data are from what <span class="math inline">\(H_0\)</span> predicts, the more extreme the test statistic.</p>
</section>
<section id="the-p-value" class="slide level2">
<h2>The p-value</h2>
<p>The <strong>p-value</strong> is the probability of obtaining results <em>at least as extreme as those observed</em>, assuming the null hypothesis is true.</p>
<p><span class="math display">\[p\text{-value} = P(\text{observed result or more extreme} \mid H_0 \text{ is true})\]</span></p>
<ul>
<li>A <strong>small p-value</strong> means the observed data would be very unlikely if <span class="math inline">\(H_0\)</span> were true <span class="math inline">\(\rightarrow\)</span> <strong>evidence against <span class="math inline">\(H_0\)</span></strong></li>
<li>A <strong>large p-value</strong> means the observed data are consistent with <span class="math inline">\(H_0\)</span> <span class="math inline">\(\rightarrow\)</span> <strong>insufficient evidence to reject <span class="math inline">\(H_0\)</span></strong></li>
</ul>
</section>
<section id="the-significance-level-α" class="slide level2">
<h2>The Significance Level (α)</h2>
<p>The <strong>significance level</strong> <span class="math inline">\(\alpha\)</span> is the threshold we set in advance for deciding whether the p-value is “small enough” to reject <span class="math inline">\(H_0\)</span>.</p>
<p>The most common choice in health research is <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Decision Rule</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>If <span class="math inline">\(p\text{-value} \leq \alpha\)</span></td>
<td><strong>Reject <span class="math inline">\(H_0\)</span></strong> — result is statistically significant</td>
</tr>
<tr class="even">
<td>If <span class="math inline">\(p\text{-value} &gt; \alpha\)</span></td>
<td><strong>Fail to reject <span class="math inline">\(H_0\)</span></strong> — insufficient evidence</td>
</tr>
</tbody>
</table>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Common Misinterpretations</strong></p>
</div>
<div class="callout-content">
<p><strong>“Failing to reject <span class="math inline">\(H_0\)</span>” is NOT the same as proving <span class="math inline">\(H_0\)</span> is true.</strong> It simply means the data do not provide strong enough evidence against it.</p>
<p><strong>“Statistically significant” does NOT necessarily mean clinically important.</strong> With a very large sample, even a trivially small difference can become statistically significant. Always consider the practical meaning of results.</p>
</div>
</div>
</div>
</section>
<section id="two-ways-to-make-the-decision-critical-value-or-p-value" class="slide level2">
<h2>Two Ways to Make the Decision: Critical Value or p-value</h2>
<p>There are two equivalent ways to decide whether to reject <span class="math inline">\(H_0\)</span>. They <strong>always give the same decision</strong>.</p>
<p><strong>1. Critical value approach (calculating by hand).</strong> The <strong>critical value</strong> is the cut-off from a statistical table (Z, t or <span class="math inline">\(\chi^2\)</span>) that marks the most extreme <span class="math inline">\(\alpha\)</span> of the distribution. We use the same left-cumulative notation as in Chapter 4. For a two-tailed test at <span class="math inline">\(\alpha = 0.05\)</span> the cut-off is at <span class="math inline">\(1 - \alpha/2 = 0.975\)</span>, for example <span class="math inline">\(t_{0.975,\,9} = 2.262\)</span>.</p>
<ul>
<li>If <span class="math inline">\(|\text{test statistic}| &gt;\)</span> critical value <span class="math inline">\(\rightarrow\)</span> <strong>reject <span class="math inline">\(H_0\)</span></strong></li>
<li>If <span class="math inline">\(|\text{test statistic}| \leq\)</span> critical value <span class="math inline">\(\rightarrow\)</span> <strong>do not reject <span class="math inline">\(H_0\)</span></strong></li>
</ul>
<p><em>(The rank tests later in this chapter also use this rule: we convert their test statistic to a Z-score first.)</em></p>
<p><strong>2. p-value approach (reading SPSS output).</strong> An exact p-value is hard to find by hand, but SPSS calculates it for us (the column <strong>Sig.</strong>). We compare it with <span class="math inline">\(\alpha\)</span> as in the table above.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-critical" class="quarto-float quarto-figure quarto-figure-center" data-fig-align="center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-critical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="ch05_files/figure-revealjs/fig-critical-1.png" class="quarto-figure quarto-figure-center" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-critical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Two-tailed test at alpha = 0.05 with df = 9: reject H0 when the test statistic falls in a red tail beyond the critical value 2.262
</figcaption>
</figure>
</div>
</div>
</div>
<p>In this book, worked examples use the <strong>critical value</strong> for the hand calculation and then show the <strong>p-value</strong> that SPSS would report, so you can see that both lead to the same conclusion. In the lab, you will use the p-value.</p>
</section>
<section id="type-i-and-type-ii-errors" class="slide level2">
<h2>Type I and Type II Errors</h2>
<p>When making a decision about <span class="math inline">\(H_0\)</span>, two types of errors are possible:</p>
<div class="cell">
<div id="tbl-errors" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-errors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Type I and Type II Errors in Hypothesis Testing
</figcaption>
<div aria-describedby="tbl-errors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-bordered cell caption-top" style="font-size: 13px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Our Decision</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">H0 is TRUE</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">H0 is FALSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Reject H0</td>
<td style="text-align: center; background-color: rgba(253, 224, 217, 1) !important;">Type I Error (alpha) - False Positive</td>
<td style="text-align: center; background-color: rgba(217, 240, 211, 1) !important;">Correct Decision (Power = 1 - beta)</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Fail to reject H0</td>
<td style="text-align: center; background-color: rgba(217, 240, 211, 1) !important;">Correct Decision</td>
<td style="text-align: center; background-color: rgba(253, 224, 217, 1) !important;">Type II Error (beta) - False Negative</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ul>
<li><strong>Type I error (α):</strong> Concluding there is an effect when there is none (<em>false positive</em>). Controlled by choosing α (usually 0.05).</li>
<li><strong>Type II error (β):</strong> Missing a real effect (<em>false negative</em>). The probability of correctly detecting a real effect is called <strong>power</strong> = <span class="math inline">\(1 - \beta\)</span>.</li>
</ul>
</section>
<section id="general-steps-in-hypothesis-testing" class="slide level2">
<h2>General Steps in Hypothesis Testing</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The 5-Step Framework</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1 — State the hypotheses:</strong> Write <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_1\)</span> clearly.</p>
<p><strong>Step 2 — Choose the significance level:</strong> Usually <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p><strong>Step 3 — Select and compute the test statistic:</strong> Choose the test that matches the data type and study design, and calculate its test statistic.</p>
<p><strong>Step 4 — Compare:</strong> By hand, compare the test statistic with the <strong>critical value</strong> from the table; with SPSS, read the <strong>p-value</strong> (Sig.).</p>
<p><strong>Step 5 — Make a decision and interpret:</strong> Reject or do not reject <span class="math inline">\(H_0\)</span>, then state your conclusion in the context of the problem — including the <strong>direction</strong> of any difference.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="statistical-testing-on-categorical-data" class="title-slide slide level1 center">
<h1>Statistical Testing on Categorical Data</h1>

</section>
<section id="chi-square-test-for-two-independent-groups" class="slide level2 scrollable">
<h2>Chi-Square Test for Two Independent Groups</h2>
<h3 id="when-to-use">When to Use</h3>
<p>The <strong>chi-square test of independence</strong> is used when:</p>
<ul>
<li>The outcome variable is <strong>categorical (nominal)</strong></li>
<li>We are comparing <strong>two or more independent groups</strong></li>
<li>We want to test whether there is an <strong>association</strong> between two categorical variables</li>
</ul>
<h3 id="the-contingency-table">The Contingency Table</h3>
<p>Data are arranged in a <strong>contingency table</strong> (also called a cross-tabulation):</p>
<p><span class="math display">\[\begin{array}{|l|c|c|c|}
\hline
&amp; \textbf{Outcome: Yes} &amp; \textbf{Outcome: No} &amp; \textbf{Row Total} \\
\hline
\textbf{Group 1} &amp; a &amp; b &amp; a+b \\
\textbf{Group 2} &amp; c &amp; d &amp; c+d \\
\hline
\textbf{Column Total} &amp; a+c &amp; b+d &amp; n \\
\hline
\end{array}\]</span></p>
<h3 id="the-test-statistic-1">The Test Statistic</h3>
<p><span class="math display">\[\chi^2 = \sum \frac{(O - E)^2}{E}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(O\)</span> = observed frequency (actual count in each cell)</li>
<li><span class="math inline">\(E\)</span> = expected frequency = <span class="math inline">\(\dfrac{\text{Row total} \times \text{Column total}}{n}\)</span></li>
</ul>
<p>The sum is taken over <strong>all cells</strong> in the table. The expected frequency is the count we would expect in a cell <strong>if <span class="math inline">\(H_0\)</span> were true</strong> (no association), so a large <span class="math inline">\(\chi^2\)</span> means the observed counts are far from what <span class="math inline">\(H_0\)</span> predicts.</p>
<p>The test statistic follows a <strong>chi-square distribution</strong> with <span class="math inline">\(df = (\text{rows} - 1) \times (\text{columns} - 1)\)</span>.</p>
<p>For a <span class="math inline">\(2 \times 2\)</span> table: <span class="math inline">\(df = (2-1)(2-1) = 1\)</span>.</p>
<p>Because <span class="math inline">\(\chi^2\)</span> is a sum of squares, it is never negative, and only <strong>large</strong> values are evidence against <span class="math inline">\(H_0\)</span>. The critical value therefore uses the left cumulative probability <span class="math inline">\(1 - \alpha\)</span>: at <span class="math inline">\(\alpha = 0.05\)</span> and <span class="math inline">\(df = 1\)</span>, <span class="math inline">\(\chi^2_{0.95,\,1} = 3.841\)</span>.</p>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Condition for Valid Chi-Square Test</strong></p>
</div>
<div class="callout-content">
<p>All <strong>expected frequencies</strong> must be <span class="math inline">\(\geq 5\)</span>. If this condition is violated, use <strong>Fisher’s exact test</strong> instead (available in SPSS).</p>
</div>
</div>
</div>
<h3 id="chi-square-critical-values">Chi-Square Critical Values</h3>
<div class="cell">
<div id="tbl-chisq" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-chisq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Chi-Square Critical Values at alpha = 0.05 (left cumulative probability 0.95)
</figcaption>
<div aria-describedby="tbl-chisq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-bordered cell caption-top" style="font-size: 13px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Degrees of Freedom (df)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">chi2(0.95, df)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important; background-color: rgba(234, 244, 251, 1) !important;">1</td>
<td style="text-align: center; background-color: rgba(234, 244, 251, 1) !important;">3.841</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">2</td>
<td style="text-align: center;">5.991</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">3</td>
<td style="text-align: center;">7.815</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">4</td>
<td style="text-align: center;">9.488</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">5</td>
<td style="text-align: center;">11.070</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">6</td>
<td style="text-align: center;">12.592</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">7</td>
<td style="text-align: center;">14.067</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">8</td>
<td style="text-align: center;">15.507</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">9</td>
<td style="text-align: center;">16.919</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">10</td>
<td style="text-align: center;">18.307</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Reading the SPSS Output (Crosstabs)</strong></p>
</div>
<div class="callout-content">
<p>SPSS prints several rows in the <strong>Chi-Square Tests</strong> table. In this course:</p>
<ol type="1">
<li>First read the <strong>footnote</strong> under the table, e.g. <em>“0 cells (0.0%) have expected count less than 5.”</em></li>
<li>If <strong>no</strong> cell has an expected count below 5 <span class="math inline">\(\rightarrow\)</span> read the <strong>Pearson Chi-Square</strong> row (Value, df, Asymp. Sig.).</li>
<li>If <strong>any</strong> cell has an expected count below 5 <span class="math inline">\(\rightarrow\)</span> read the <strong>Fisher’s Exact Test</strong> row instead (Exact Sig. 2-sided).</li>
</ol>
<p>The other rows (Continuity Correction, Likelihood Ratio, Linear-by-Linear Association) are not used in this course.</p>
</div>
</div>
</div>
</section>
<section id="example-1-chi-square-test" class="slide level2">
<h2>Example 1: Chi-Square Test</h2>
<p>A cross-sectional study investigates whether <strong>smoking status</strong> is associated with <strong>hypertension</strong> in a sample of 200 adults.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Hypertension</th>
<th style="text-align: center;">No Hypertension</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Smoker</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">100</td>
</tr>
<tr class="even">
<td>Non-smoker</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">100</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;"><strong>70</strong></td>
<td style="text-align: center;"><strong>130</strong></td>
<td style="text-align: center;"><strong>200</strong></td>
</tr>
</tbody>
</table>
<p>Test at <span class="math inline">\(\alpha = 0.05\)</span> whether smoking is associated with hypertension.</p>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1 — Hypotheses:</strong></p>
<p><span class="math inline">\(H_0\)</span>: Smoking status and hypertension are independent (no association).</p>
<p><span class="math inline">\(H_1\)</span>: Smoking status and hypertension are associated.</p>
<p><strong>Step 2 —</strong> <span class="math inline">\(\alpha = 0.05\)</span></p>
<p><strong>Step 3 — Expected frequencies and test statistic:</strong></p>
<p><span class="math display">\[E = \frac{\text{Row total} \times \text{Column total}}{n}\]</span></p>
<div class="cell">
<div id="tbl-expected" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-expected-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Observed (O) and Expected (E) Frequencies
</figcaption>
<div aria-describedby="tbl-expected-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-bordered cell caption-top" style="font-size: 13px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Group</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">O (Hyp.)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">E (Hyp.)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">O (No Hyp.)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">E (No Hyp.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Smoker</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">65</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Non-smoker</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">65</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>All expected frequencies are <span class="math inline">\(\geq 5\)</span>, so the chi-square test is valid.</p>
<p><span class="math display">\[\chi^2 = \frac{(45-35)^2}{35} + \frac{(55-65)^2}{65} +
           \frac{(25-35)^2}{35} + \frac{(75-65)^2}{65}\]</span></p>
<p><span class="math display">\[= \frac{100}{35} + \frac{100}{65} + \frac{100}{35} + \frac{100}{65}
= 2.857 + 1.538 + 2.857 + 1.538 = \mathbf{8.791}\]</span></p>
<p><span class="math inline">\(df = (2-1)(2-1) = 1\)</span></p>
<p><strong>Step 4 — Compare:</strong></p>
<p>Critical value from the chi-square table: <span class="math inline">\(\chi^2_{0.95,\,1} = 3.841\)</span>. Since <span class="math inline">\(8.791 &gt; 3.841\)</span>, the test statistic falls in the rejection region.</p>
<p>SPSS (Pearson Chi-Square row) would report <span class="math inline">\(p = 0.003\)</span>, which is <span class="math inline">\(&lt; 0.05\)</span> — the same decision.</p>
<p><strong>Step 5 — Decision and interpretation:</strong></p>
<p>We <strong>reject <span class="math inline">\(H_0\)</span></strong>. There is a statistically significant association between smoking status and hypertension (<span class="math inline">\(\chi^2 = 8.79\)</span>, <span class="math inline">\(df = 1\)</span>, <span class="math inline">\(p = 0.003\)</span>). Smokers have a higher prevalence of hypertension (45%) than non-smokers (25%).</p>
<p><em>Because this is a cross-sectional study, the result shows an <strong>association</strong>, not that smoking <strong>causes</strong> hypertension.</em></p>
</div>
</div>
</div>
</section>
<section id="statistical-testing-on-quantitative-data" class="slide level2">
<h2>Statistical Testing on Quantitative Data</h2>
<p>The two t-tests in this section compare <strong>means</strong>. Like the confidence intervals in Chapter 4, they rely on the data (or the sample means) being approximately <strong>normal</strong>.</p>
</section>
<section id="checking-the-normality-assumption" class="slide level2">
<h2>Checking the Normality Assumption</h2>
<p>Before using a t-test, check whether the outcome is approximately normal:</p>
<ul>
<li><p><strong>Graphs:</strong> a histogram should look roughly bell-shaped, and the points on a <strong>normal Q–Q plot</strong> should lie close to the straight line.</p></li>
<li><p><strong>Tests:</strong> SPSS <em>Explore</em> reports the <strong>Kolmogorov–Smirnov</strong> and <strong>Shapiro–Wilk</strong> tests (you practise these in the lab). Their hypotheses are</p>
<p><span class="math inline">\(H_0\)</span>: the data come from a normal distribution</p>
<p><span class="math inline">\(H_1\)</span>: the data do not come from a normal distribution</p>
<p>so <strong>Sig. &gt; 0.05</strong> means <em>no evidence against normality</em> <span class="math inline">\(\rightarrow\)</span> a t-test is appropriate; <strong>Sig. <span class="math inline">\(\leq\)</span> 0.05</strong> means the data are not normal <span class="math inline">\(\rightarrow\)</span> consider a rank test (later in this chapter).</p></li>
</ul>
<p>What to check depends on the design:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Check normality of</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Independent samples t-test</td>
<td>The outcome <strong>in each group separately</strong></td>
</tr>
<tr class="even">
<td>Paired samples t-test</td>
<td>The <strong>differences</strong> <span class="math inline">\(d_i\)</span> within pairs</td>
</tr>
</tbody>
</table>
<p>With large samples (<span class="math inline">\(n \geq 30\)</span> per group) the <strong>Central Limit Theorem</strong> (Chapter 4) makes the t-test robust even if the data are somewhat skewed.</p>
</section>
<section id="independent-samples-t-test" class="slide level2">
<h2>Independent Samples t-Test</h2>
<h3 id="when-to-use-1">When to Use</h3>
<p>The <strong>independent samples t-test</strong> is used when:</p>
<ul>
<li>The outcome variable is <strong>continuous (numerical)</strong></li>
<li>We are comparing the <strong>means of two independent groups</strong></li>
<li>The data are approximately <strong>normally distributed</strong> in each group (or sample sizes are large enough, <span class="math inline">\(n \geq 30\)</span> per group)</li>
</ul>
<h3 id="hypotheses">Hypotheses</h3>
<p><span class="math display">\[H_0: \mu_1 = \mu_2 \quad \text{(no difference in population means)}\]</span> <span class="math display">\[H_1: \mu_1 \neq \mu_2 \quad \text{(the population means differ)}\]</span></p>
<h3 id="the-test-statistic-2">The Test Statistic</h3>
<p><span class="math display">\[t = \frac{\bar{x}_1 - \bar{x}_2}{SE_{\bar{x}_1 - \bar{x}_2}}\]</span></p>
<p>The standard error of the difference depends on whether the two groups have <strong>equal or unequal variances</strong>.</p>
<p><strong>Equal variances assumed (pooled):</strong></p>
<p><span class="math display">\[SE = s_p\sqrt{\frac{1}{n_1}+\frac{1}{n_2}}, \qquad
s_p = \sqrt{\frac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1+n_2-2}}\]</span></p>
<p><strong>Equal variances not assumed (Welch’s):</strong></p>
<p><span class="math display">\[SE = \sqrt{\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}}\]</span></p>
<p>The test statistic follows a <strong>t-distribution</strong> with <span class="math inline">\(df = n_1 + n_2 - 2\)</span> (equal variances) or an approximated df (Welch’s, calculated by SPSS).</p>
<h3 id="which-version-levenes-test">Which Version? Levene’s Test</h3>
<p>SPSS decides between the two versions with <strong>Levene’s test for equality of variances</strong>, printed in the first columns of the <em>Independent Samples Test</em> table:</p>
<p><span class="math inline">\(H_0: \sigma_1^2 = \sigma_2^2\)</span> (the two variances are equal)</p>
<p><span class="math inline">\(H_1: \sigma_1^2 \neq \sigma_2^2\)</span> (the variances differ)</p>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Reading the Independent Samples Test Table — Two Steps</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1 — Levene’s test (Sig. in the Levene columns):</strong></p>
<ul>
<li>Sig. <strong>&gt; 0.05</strong> <span class="math inline">\(\rightarrow\)</span> no evidence that the variances differ <span class="math inline">\(\rightarrow\)</span> read the <strong>top row</strong>, <em>“Equal variances assumed”</em>.</li>
<li>Sig. <strong><span class="math inline">\(\leq\)</span> 0.05</strong> <span class="math inline">\(\rightarrow\)</span> the variances differ <span class="math inline">\(\rightarrow\)</span> read the <strong>bottom row</strong>, <em>“Equal variances not assumed”</em>.</li>
</ul>
<p><strong>Step 2 — the t-test (Sig. (2-tailed) in the row you chose):</strong> compare with <span class="math inline">\(\alpha\)</span> to decide whether the <strong>means</strong> differ.</p>
<p>Do not confuse the two Sig. values: the first is about <strong>variances</strong>, the second is about <strong>means</strong>.</p>
</div>
</div>
</div>
<p>When you calculate by hand in this course, the question will either give you the Levene’s test result or state whether the variances can be assumed equal. You do not need to decide this yourself from the SDs.</p>
</section>
<section id="example-2-independent-samples-t-test" class="slide level2">
<h2>Example 2: Independent Samples t-Test</h2>
<p>A clinical trial compares the mean reduction in systolic blood pressure (mmHg) between patients receiving a <strong>new drug</strong> vs.&nbsp;a <strong>placebo</strong> after 8 weeks.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: center;">n</th>
<th style="text-align: center;">Mean reduction</th>
<th style="text-align: center;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>New drug</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">12.4</td>
<td style="text-align: center;">6.8</td>
</tr>
<tr class="even">
<td>Placebo</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">7.1</td>
<td style="text-align: center;">7.2</td>
</tr>
</tbody>
</table>
<p>Assume the two population variances are <strong>equal</strong>. Test at <span class="math inline">\(\alpha = 0.05\)</span> whether the mean reduction in SBP differs between the new drug and placebo.</p>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1 — Hypotheses:</strong></p>
<p><span class="math inline">\(H_0: \mu_1 = \mu_2\)</span> (no difference in mean reduction)</p>
<p><span class="math inline">\(H_1: \mu_1 \neq \mu_2\)</span> (two-tailed; difference exists)</p>
<p><strong>Step 2 —</strong> <span class="math inline">\(\alpha = 0.05\)</span></p>
<p><strong>Step 3 — Pooled standard error.</strong> The question states that the variances are equal, so we use the pooled (equal variances) formula.</p>
<p><span class="math display">\[\begin{aligned}
s_p &amp;= \sqrt{\frac{(40-1)(6.8)^2 + (40-1)(7.2)^2}{40+40-2}}
     = \sqrt{\frac{39(46.24) + 39(51.84)}{78}} \\
    &amp;= \sqrt{\frac{1803.36 + 2021.76}{78}}
     = \sqrt{49.041} = 7.003
\end{aligned}\]</span></p>
<p><span class="math display">\[SE = 7.003 \times \sqrt{\frac{1}{40}+\frac{1}{40}}
= 7.003 \times \sqrt{0.05}
= 7.003 \times 0.2236 = 1.566\]</span></p>
<p><span class="math display">\[t = \frac{12.4 - 7.1}{1.566} = \frac{5.3}{1.566} = \mathbf{3.384}\]</span></p>
<p><span class="math inline">\(df = 40 + 40 - 2 = 78\)</span></p>
<p><strong>Step 4 — Compare:</strong></p>
<p><span class="math inline">\(df = 78\)</span> is not listed in the t-table, so we use the next smaller df, 70: <span class="math inline">\(t_{0.975,\,70} = 1.994\)</span> (the exact value for <span class="math inline">\(df = 78\)</span> is 1.991).</p>
<p>Since <span class="math inline">\(3.384 &gt; 1.994\)</span>, the test statistic falls in the rejection region. SPSS would report <span class="math inline">\(p = 0.001\)</span>, which is <span class="math inline">\(&lt; 0.05\)</span>.</p>
<p><strong>Step 5 — Decision and interpretation:</strong></p>
<p>We <strong>reject <span class="math inline">\(H_0\)</span></strong>. The mean reduction in systolic blood pressure differs significantly between the two groups (<span class="math inline">\(t = 3.38\)</span>, <span class="math inline">\(df = 78\)</span>, <span class="math inline">\(p = 0.001\)</span>). The new drug group had the <strong>larger</strong> mean reduction: 12.4 vs.&nbsp;7.1 mmHg, a difference of 5.3 mmHg (95% CI: 2.2 to 8.4 mmHg).</p>
</div>
</div>
</div>
</section>
<section id="paired-samples-t-test" class="slide level2">
<h2>Paired Samples t-Test</h2>
<h3 id="when-to-use-2">When to Use</h3>
<p>The <strong>paired samples t-test</strong> is used when:</p>
<ul>
<li>The outcome variable is <strong>continuous (numerical)</strong></li>
<li>Observations come in <strong>natural pairs</strong> — the same subject measured twice (e.g., before and after treatment), or matched pairs of subjects</li>
<li>We want to test whether the <strong>mean difference</strong> within pairs is zero</li>
<li>The <strong>differences</strong> are approximately normally distributed</li>
</ul>
<h3 id="hypotheses-1">Hypotheses</h3>
<p><span class="math display">\[H_0: \mu_d = 0 \quad \text{(mean difference is zero)}\]</span> <span class="math display">\[H_1: \mu_d \neq 0 \quad \text{(mean difference is not zero)}\]</span></p>
<p>Where <span class="math inline">\(\mu_d\)</span> is the population mean of the within-pair differences.</p>
<h3 id="the-test-statistic-3">The Test Statistic</h3>
<p>For each pair <span class="math inline">\(i\)</span>, compute the difference: <span class="math inline">\(d_i = x_{1i} - x_{2i}\)</span></p>
<p>Then:</p>
<p><span class="math display">\[t = \frac{\bar{d}}{s_d / \sqrt{n}}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\bar{d}\)</span> = mean of the differences</li>
<li><span class="math inline">\(s_d\)</span> = standard deviation of the differences</li>
<li><span class="math inline">\(n\)</span> = number of pairs</li>
</ul>
<p>The test statistic follows a <strong>t-distribution</strong> with <span class="math inline">\(df = n - 1\)</span>.</p>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why Not Use the Independent t-Test for Paired Data?</strong></p>
</div>
<div class="callout-content">
<p>Each patient is compared <strong>with themselves</strong>, so differences between patients (age, weight, baseline health) cancel out. Working with the differences <span class="math inline">\(d_i\)</span> turns two columns of data into <strong>one</strong>, and the test becomes a one-sample test of whether the mean difference is 0.</p>
</div>
</div>
</div>
</section>
<section id="example-3-paired-samples-t-test" class="slide level2">
<h2>Example 3: Paired Samples t-Test</h2>
<p>A study measures the <strong>diastolic blood pressure (DBP)</strong> of 10 patients <strong>before</strong> and <strong>after</strong> 4 weeks of a lifestyle intervention.</p>
<div class="cell">
<div id="tbl-paired" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-paired-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: DBP Before and After Lifestyle Intervention (n = 10 patients)
</figcaption>
<div aria-describedby="tbl-paired-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-bordered cell caption-top" style="font-size: 13px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(44, 123, 182, 1) !important;">Patient</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 123, 182, 1) !important;">DBP Before (mmHg)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 123, 182, 1) !important;">DBP After (mmHg)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 123, 182, 1) !important;">Difference d = Before - After</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Patient 1</td>
<td style="text-align: center;">92</td>
<td style="text-align: center;">85</td>
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Patient 2</td>
<td style="text-align: center;">88</td>
<td style="text-align: center;">82</td>
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Patient 3</td>
<td style="text-align: center;">95</td>
<td style="text-align: center;">89</td>
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Patient 4</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">91</td>
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Patient 5</td>
<td style="text-align: center;">85</td>
<td style="text-align: center;">80</td>
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Patient 6</td>
<td style="text-align: center;">97</td>
<td style="text-align: center;">88</td>
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Patient 7</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">84</td>
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Patient 8</td>
<td style="text-align: center;">94</td>
<td style="text-align: center;">87</td>
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Patient 9</td>
<td style="text-align: center;">88</td>
<td style="text-align: center;">83</td>
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Patient 10</td>
<td style="text-align: center;">96</td>
<td style="text-align: center;">88</td>
<td style="text-align: center; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">8</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Test at <span class="math inline">\(\alpha = 0.05\)</span> whether the mean DBP changed after the intervention. Assume the differences are approximately normally distributed.</p>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1 — Hypotheses:</strong></p>
<p><span class="math inline">\(H_0: \mu_d = 0\)</span> (no mean change in DBP)</p>
<p><span class="math inline">\(H_1: \mu_d \neq 0\)</span> (mean DBP has changed)</p>
<p><strong>Step 2 —</strong> <span class="math inline">\(\alpha = 0.05\)</span></p>
<p><strong>Step 3 — Compute <span class="math inline">\(\bar{d}\)</span>, <span class="math inline">\(s_d\)</span> and the test statistic:</strong></p>
<p><span class="math display">\[\bar{d} = \frac{68}{10} = 6.8 \text{ mmHg}\]</span></p>
<p><span class="math display">\[s_d = \sqrt{\frac{\sum(d_i - \bar{d})^2}{n-1}} = 1.476\]</span></p>
<p><span class="math display">\[t = \frac{\bar{d}}{s_d/\sqrt{n}} = \frac{6.8}{1.476/\sqrt{10}}
= \frac{6.8}{0.467} = 14.571\]</span></p>
<p><span class="math inline">\(df = n - 1 = 9\)</span></p>
<p><strong>Step 4 — Compare:</strong></p>
<p><span class="math inline">\(t_{0.975,\,9} = 2.262\)</span>. Since <span class="math inline">\(14.571 &gt; 2.262\)</span>, the test statistic falls in the rejection region. SPSS would report <span class="math inline">\(p &lt; 0.001\)</span>.</p>
<p><strong>Step 5 — Decision and interpretation:</strong></p>
<p>We <strong>reject <span class="math inline">\(H_0\)</span></strong>. Mean diastolic blood pressure changed significantly after the intervention (<span class="math inline">\(t = 14.57\)</span>, <span class="math inline">\(df = 9\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>). Because <span class="math inline">\(\bar{d}\)</span> = Before − After is positive, DBP <strong>decreased</strong>, by <strong>6.8 mmHg</strong> on average.</p>
</div>
</div>
</div>
</section>
<section id="statistical-testing-on-rank-data" class="slide level2">
<h2>Statistical Testing on Rank Data</h2>
<p>The t-tests need <strong>numerical</strong> data that are approximately <strong>normal</strong>. When the outcome is <strong>ordinal</strong> (such as a pain score) or the normality check fails, we use <strong>rank tests</strong> instead. Rank tests replace each value by its <strong>rank</strong> (1st, 2nd, 3rd, …) and do not assume any particular distribution — they are called <strong>non-parametric</strong> tests.</p>
<p>Each t-test has a rank-test partner:</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Design</th>
<th>Numerical, normal</th>
<th>Ordinal, or not normal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two <strong>independent</strong> groups</td>
<td>Independent samples t-test</td>
<td><strong>Mann-Whitney U test</strong></td>
</tr>
<tr class="even">
<td>Two <strong>related</strong> (paired) measurements</td>
<td>Paired samples t-test</td>
<td><strong>Wilcoxon signed-ranks test</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Rank Tests Use the Z-Table You Already Know</strong></p>
</div>
<div class="callout-content">
<p>The rank tests have their own statistics (<span class="math inline">\(U\)</span> and <span class="math inline">\(W\)</span>), but we do not need a new table. We convert <span class="math inline">\(U\)</span> or <span class="math inline">\(W\)</span> to a <strong>Z-score</strong> — exactly what SPSS does — and then use the same rule as in Chapter 3 and Chapter 4:</p>
<p><span class="math display">\[\text{reject } H_0 \text{ if } |z| &gt; z_{0.975} = 1.96 \quad (\alpha = 0.05,\ \text{two-tailed})\]</span></p>
</div>
</div>
</div>
</section>
<section id="mann-whitney-u-test-for-two-independent-groups" class="slide level2 scrollable">
<h2>Mann-Whitney U Test for Two Independent Groups</h2>
<h3 id="when-to-use-3">When to Use</h3>
<p>The <strong>Mann-Whitney U test</strong> (also called the Wilcoxon rank-sum test) is used when:</p>
<ul>
<li>The outcome variable is <strong>ordinal</strong>, or</li>
<li>The outcome is <strong>continuous but not normally distributed</strong> (especially with small samples or obvious skewness)</li>
<li>We are comparing <strong>two independent groups</strong></li>
</ul>
<p>It is the non-parametric alternative to the <strong>independent samples t-test</strong>.</p>
<h3 id="hypotheses-2">Hypotheses</h3>
<p><span class="math inline">\(H_0\)</span>: the outcome values in the two groups are equal (the two groups come from the same distribution)</p>
<p><span class="math inline">\(H_1\)</span>: the outcome values in the two groups are different</p>
<h3 id="how-it-works">How It Works</h3>
<p>Instead of comparing means, the Mann-Whitney test compares the <strong>ranks</strong> of observations between the two groups.</p>
<p><strong>Steps:</strong></p>
<ol type="1">
<li>Combine all observations from both groups and <strong>rank them</strong> from smallest (rank 1) to largest.</li>
<li>If there are <strong>tied values</strong>, assign the average rank to each tied observation.</li>
<li>Calculate the <strong>sum of ranks</strong> for each group: <span class="math inline">\(W_1\)</span> and <span class="math inline">\(W_2\)</span>.</li>
<li>Calculate the test statistic <span class="math inline">\(U\)</span> from the rank sums (formula below).</li>
<li>Convert <span class="math inline">\(U\)</span> to a <strong>Z-score</strong> (below) and compare <span class="math inline">\(|z|\)</span> with 1.96. SPSS reports this Z-score and its p-value.</li>
</ol>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Intuition Behind the Test</strong></p>
</div>
<div class="callout-content">
<p>If the two groups come from the same distribution, their ranks should be <strong>randomly mixed</strong> between the groups — neither group should consistently have higher or lower ranks. A significant result means one group consistently has higher ranks (i.e., higher values) than the other.</p>
</div>
</div>
</div>
<h3 id="the-u-statistic">The U Statistic</h3>
<p><span class="math display">\[U_1 = n_1 n_2 + \frac{n_1(n_1+1)}{2} - W_1\]</span></p>
<p><span class="math display">\[U_2 = n_1 n_2 + \frac{n_2(n_2+1)}{2} - W_2\]</span></p>
<p><span class="math display">\[U = \min(U_1, U_2)\]</span></p>
<p>Where <span class="math inline">\(n_1\)</span>, <span class="math inline">\(n_2\)</span> are the sample sizes and <span class="math inline">\(W_1\)</span>, <span class="math inline">\(W_2\)</span> are the rank sums for groups 1 and 2 respectively. As a check, <span class="math inline">\(U_1 + U_2 = n_1 n_2\)</span>.</p>
<p>A <strong>small</strong> <span class="math inline">\(U\)</span> means the two groups hardly overlap — evidence against <span class="math inline">\(H_0\)</span>.</p>
<h3 id="converting-u-to-a-z-score">Converting U to a Z-Score</h3>
<p>If <span class="math inline">\(H_0\)</span> is true, <span class="math inline">\(U\)</span> is centred at <span class="math inline">\(n_1 n_2 / 2\)</span> (half of the largest possible value). We standardise it like any Z-score — <em>(value − mean) / SD</em>:</p>
<p><span class="math display">\[\mu_U = \frac{n_1 n_2}{2}, \qquad
\sigma_U = \sqrt{\frac{n_1 n_2 (n_1 + n_2 + 1)}{12}}, \qquad
z = \frac{U - \mu_U}{\sigma_U}\]</span></p>
<ul>
<li><strong>Decision:</strong> reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(|z| &gt; 1.96\)</span>.</li>
<li><strong>p-value (optional):</strong> <span class="math inline">\(p = 2 \times P(Z &lt; -|z|) = 2\,[\,1 - P(Z &lt; |z|)\,]\)</span>, read from the Z-table.</li>
</ul>
<p>Because <span class="math inline">\(U = \min(U_1, U_2)\)</span> is the smaller value, <span class="math inline">\(z\)</span> is always zero or negative. SPSS prints the same Z-score in its <em>Test Statistics</em> table.</p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why Your Z May Differ Slightly From SPSS</strong></p>
</div>
<div class="callout-content">
<p>When there are <strong>tied values</strong>, SPSS adjusts <span class="math inline">\(\sigma_U\)</span> for the ties, so its Z-score can differ from the hand calculation in the second decimal place. The decision is the same in practice. The Z-approximation is most accurate when each group has about 10 or more observations; SPSS uses the same approximation for its <em>Asymp. Sig.</em> value.</p>
</div>
</div>
</div>
</section>
<section id="example-4-mann-whitney-u-test" class="slide level2">
<h2>Example 4: Mann-Whitney U Test</h2>
<p>Pain score (0–10, <strong>ordinal</strong>) was recorded 24 hours after surgery in <strong>12 patients</strong>: 6 received the standard analgesic regimen and 6 received a new regimen. The two groups are different patients, so they are <strong>independent</strong>.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Regimen</th>
<th>Pain scores</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Standard</td>
<td>6, 7, 5, 8, 6, 7</td>
</tr>
<tr class="even">
<td>New</td>
<td>3, 4, 5, 2, 4, 6</td>
</tr>
</tbody>
</table>
<p>Test at <span class="math inline">\(\alpha = 0.05\)</span> whether pain scores differ between the two regimens.</p>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Hypotheses:</strong> <span class="math inline">\(H_0\)</span>: pain scores in the two groups are equal; <span class="math inline">\(H_1\)</span>: pain scores in the two groups are different. <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<div class="cell">
<div id="tbl-mw-ranks" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mw-ranks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Pain scores and their ranks (n1 = n2 = 6)
</figcaption>
<div aria-describedby="tbl-mw-ranks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-bordered cell caption-top" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(44, 123, 182, 1) !important;">Group</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 123, 182, 1) !important;">Pain score</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 123, 182, 1) !important;">Rank (combined)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">New</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">New</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">New</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Standard</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">5.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">New</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">5.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Standard</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">8.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Standard</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">8.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">8.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Standard</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">10.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Standard</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">10.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Standard</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">12.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Step 1 — Rank all 12 scores together.</strong> Ties share the average rank: the two 4s occupy ranks 3 and 4, so each gets 3.5; the three 6s occupy ranks 7, 8 and 9, so each gets 8.</p>
<p><strong>Step 2 — Sum the ranks in each group:</strong></p>
<p><span class="math display">\[W_{\text{Standard}} = 8 + 10.5 + 5.5 + 12 + 8 + 10.5 = 54.5\]</span> <span class="math display">\[W_{\text{New}} = 2 + 3.5 + 5.5 + 1 + 3.5 + 8 = 23.5\]</span></p>
<p>(Check: the total of ranks 1 to 12 is <span class="math inline">\(12 \times 13 / 2 = 78 = 54.5 + 23.5\)</span>.)</p>
<p><strong>Step 3 — Calculate U</strong> with <span class="math inline">\(n_1 = n_2 = 6\)</span>:</p>
<p><span class="math display">\[U_1 = 36 + \frac{6 \times 7}{2} - 54.5 = 36 + 21 - 54.5 = 2.5\]</span> <span class="math display">\[U_2 = 36 + 21 - 23.5 = 33.5\]</span> <span class="math display">\[U = \min(2.5,\; 33.5) = 2.5\]</span></p>
<p><strong>Step 4 — Convert U to a Z-score</strong> with <span class="math inline">\(n_1 = n_2 = 6\)</span>:</p>
<p><span class="math display">\[\mu_U = \frac{6 \times 6}{2} = 18, \qquad
\sigma_U = \sqrt{\frac{6 \times 6 \times 13}{12}} = \sqrt{39} = 6.245\]</span></p>
<p><span class="math display">\[z = \frac{2.5 - 18}{6.245} = -2.48\]</span></p>
<p>Since <span class="math inline">\(|z| = 2.48 &gt; 1.96\)</span>, the result is significant. From the Z-table, <span class="math inline">\(p = 2 \times (1 - 0.9934) = 0.013\)</span>.</p>
<p>SPSS reports <span class="math inline">\(Z = -2.513\)</span> and <span class="math inline">\(p\)</span> (Asymp. Sig. 2-tailed) <span class="math inline">\(= 0.012\)</span> — the same decision (the small difference is the tie adjustment).</p>
<p><strong>Step 5 — Decision.</strong> We <strong>reject <span class="math inline">\(H_0\)</span></strong>. Pain scores differ significantly between the two regimens. The mean rank of the new regimen (<span class="math inline">\(23.5 / 6 = 3.9\)</span>) is lower than that of the standard regimen (<span class="math inline">\(54.5 / 6 = 9.1\)</span>), so patients on the <strong>new regimen reported less pain</strong>.</p>
</div>
</div>
</div>
</section>
<section id="wilcoxon-signed-ranks-test-for-two-related-groups" class="slide level2 scrollable">
<h2>Wilcoxon Signed-Ranks Test for Two Related Groups</h2>
<h3 id="when-to-use-4">When to Use</h3>
<p>The <strong>Wilcoxon signed-ranks test</strong> (also called the Wilcoxon matched-pairs test) is the non-parametric alternative to the <strong>paired samples t-test</strong>. It is used when:</p>
<ul>
<li>The outcome variable is <strong>ordinal</strong>, or</li>
<li>The <strong>differences</strong> between pairs are <strong>not normally distributed</strong> (especially with small samples)</li>
<li>The two sets of measurements are <strong>related (paired)</strong> — for example, the same patients measured before and after treatment, or two measurements taken on the same blood sample</li>
</ul>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Mann-Whitney or Wilcoxon?</strong></p>
</div>
<div class="callout-content">
<p>Both tests work with ranks, so they are easy to confuse. The difference is the <strong>study design</strong>, exactly as with the two t-tests:</p>
<ul>
<li><strong>Two independent groups</strong> (different people in each group) <span class="math inline">\(\rightarrow\)</span> <strong>Mann-Whitney U test</strong></li>
<li><strong>Two related groups</strong> (the same people measured twice) <span class="math inline">\(\rightarrow\)</span> <strong>Wilcoxon signed-ranks test</strong></li>
</ul>
</div>
</div>
</div>
<h3 id="hypotheses-3">Hypotheses</h3>
<p><span class="math inline">\(H_0\)</span>: the two related measurements are equal</p>
<p><span class="math inline">\(H_1\)</span>: the two related measurements are different</p>
<h3 id="how-it-works-1">How It Works</h3>
<p>The Wilcoxon test looks at the <strong>differences within each pair</strong>, and then ranks the <strong>sizes</strong> of those differences.</p>
<p><strong>Steps:</strong></p>
<ol type="1">
<li>For each pair, calculate the difference <span class="math inline">\(d_i = x_{i,1} - x_{i,2}\)</span>.</li>
<li><strong>Discard</strong> any pair whose difference is zero.</li>
<li>Rank the <strong>absolute</strong> differences <span class="math inline">\(|d_i|\)</span> from smallest to largest, assigning average ranks to ties.</li>
<li>Attach to each rank the <strong>sign</strong> of its original difference.</li>
<li>Add the ranks belonging to the positive differences (<span class="math inline">\(W^{+}\)</span>) and the ranks belonging to the negative differences (<span class="math inline">\(W^{-}\)</span>).</li>
</ol>
<h3 id="the-test-statistic-4">The Test Statistic</h3>
<p><span class="math display">\[W = \min(W^{+},\; W^{-})\]</span></p>
<p>If the two conditions really are the same, the positive and negative ranks should roughly balance, so <span class="math inline">\(W^{+}\)</span> and <span class="math inline">\(W^{-}\)</span> should be similar. A <strong>small</strong> value of <span class="math inline">\(W\)</span> means the differences fall mostly in one direction, which is evidence against <span class="math inline">\(H_0\)</span>.</p>
<h3 id="converting-w-to-a-z-score">Converting W to a Z-Score</h3>
<p><span class="math inline">\(n\)</span> is the number of pairs <strong>after discarding zero differences</strong>. If <span class="math inline">\(H_0\)</span> is true, <span class="math inline">\(W\)</span> is centred at half of the total of all ranks:</p>
<p><span class="math display">\[\mu_W = \frac{n(n+1)}{4}, \qquad
\sigma_W = \sqrt{\frac{n(n+1)(2n+1)}{24}}, \qquad
z = \frac{W - \mu_W}{\sigma_W}\]</span></p>
<p>As with Mann-Whitney: <strong>reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(|z| &gt; 1.96\)</span></strong>, and SPSS reports this Z-score (adjusted for ties) in its <em>Test Statistics</em> table.</p>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Reading the SPSS Output</strong></p>
</div>
<div class="callout-content">
<p>Choose <strong>Analyze</strong> <span class="math inline">\(\rightarrow\)</span> <strong>Nonparametric Tests</strong> <span class="math inline">\(\rightarrow\)</span> <strong>Legacy Dialogs</strong> <span class="math inline">\(\rightarrow\)</span> <strong>2 Related Samples</strong>, and tick <strong>Wilcoxon</strong> (older SPSS versions, as in the lab manual, have no <em>Legacy Dialogs</em> step). The <em>Ranks</em> table shows the sum of the negative and positive ranks, and the <em>Test Statistics</em> table reports <span class="math inline">\(Z\)</span> and the 2-tailed significance. As always, decide by comparing the p-value with <span class="math inline">\(\alpha\)</span> — the sign of <span class="math inline">\(Z\)</span> only indicates the direction of the ranks, not the importance of the result.</p>
</div>
</div>
</div>
</section>
<section id="example-5-wilcoxon-signed-ranks-test" class="slide level2">
<h2>Example 5: Wilcoxon Signed-Ranks Test</h2>
<p>Blood clotting time (minutes) was measured for <strong>8 patients</strong> using two solutions: an extract from shrimp shells (“Shrimp”) and the standard solution (“Standard”). Blood was taken from each patient and divided into two parts, so the two measurements are <strong>paired</strong>.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Patient</th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">5</th>
<th style="text-align: center;">6</th>
<th style="text-align: center;">7</th>
<th style="text-align: center;">8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Shrimp</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td>Standard</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">9</td>
</tr>
</tbody>
</table>
<p>The sample is small (<span class="math inline">\(n = 8\)</span>), so we cannot rely on the normality of the differences. Test at <span class="math inline">\(\alpha = 0.05\)</span> whether the clotting times differ, using the <strong>Wilcoxon signed-ranks test</strong>.</p>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Hypotheses:</strong> <span class="math inline">\(H_0\)</span>: the clotting times with the two solutions are equal; <span class="math inline">\(H_1\)</span>: they are different. <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<div class="cell">
<div id="tbl-wilcoxon" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-wilcoxon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Blood clotting time using two solutions (n = 8 patients), with signed ranks
</figcaption>
<div aria-describedby="tbl-wilcoxon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-bordered cell caption-top" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 123, 182, 1) !important;">Patient</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 123, 182, 1) !important;">Shrimp</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 123, 182, 1) !important;">Standard</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 123, 182, 1) !important;">d</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 123, 182, 1) !important;">abs(d)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 123, 182, 1) !important;">Rank of abs(d)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(44, 123, 182, 1) !important;">Signed rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">-4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">7.5</td>
<td style="text-align: center;">-7.5</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">-1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">-1.5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4.5</td>
<td style="text-align: center;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">-4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">7.5</td>
<td style="text-align: center;">-7.5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">-2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4.5</td>
<td style="text-align: center;">-4.5</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">-2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4.5</td>
<td style="text-align: center;">-4.5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">-2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4.5</td>
<td style="text-align: center;">-4.5</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Step 1 — Differences</strong> <span class="math inline">\(d = \text{Shrimp} - \text{Standard}\)</span>: none is zero, so all 8 pairs are kept.</p>
<p><strong>Step 2 — Rank <span class="math inline">\(|d|\)</span> with average ranks for ties:</strong> the two 1s share ranks 1–2 (each 1.5); the four 2s share ranks 3–6 (each 4.5); the two 4s share ranks 7–8 (each 7.5).</p>
<p><strong>Step 3 — Sum the signed ranks:</strong></p>
<p><span class="math display">\[W^{+} = 4.5 \;(\text{patient } 3) + 1.5 \;(\text{patient } 7) = 6\]</span> <span class="math display">\[W^{-} = 7.5 + 1.5 + 7.5 + 4.5 + 4.5 + 4.5 = 30 \quad (\text{patients } 1, 2, 4, 5, 6, 8)\]</span></p>
<p>(Check: <span class="math inline">\(W^{+} + W^{-} = 8 \times 9 / 2 = 36\)</span>.)</p>
<p><span class="math display">\[W = \min(6,\; 30) = 6\]</span></p>
<p><strong>Step 4 — Convert W to a Z-score</strong> with <span class="math inline">\(n = 8\)</span> pairs:</p>
<p><span class="math display">\[\mu_W = \frac{8 \times 9}{4} = 18, \qquad
\sigma_W = \sqrt{\frac{8 \times 9 \times 17}{24}} = \sqrt{51} = 7.141\]</span></p>
<p><span class="math display">\[z = \frac{6 - 18}{7.141} = -1.68\]</span></p>
<p>Since <span class="math inline">\(|z| = 1.68 \leq 1.96\)</span>, the result is not significant. From the Z-table, <span class="math inline">\(p = 2 \times (1 - 0.9535) = 0.093\)</span>.</p>
<p>SPSS reports <span class="math inline">\(Z = -1.706\)</span> and <span class="math inline">\(p = 0.088\)</span> — the same decision. <em>(SPSS calculates the difference as Standard − Shrimp, so its Ranks table lists the 6 and the 30 the other way round; <span class="math inline">\(W\)</span> and the p-value are the same.)</em></p>
<p><strong>Step 5 — Decision.</strong> We <strong>do not reject</strong> <span class="math inline">\(H_0\)</span>. There is not enough evidence to say that the clotting times produced by the two solutions differ, at the 0.05 level of significance.</p>
</div>
</div>
</div>
</section>
<section id="choosing-the-right-test" class="slide level2">
<h2>Choosing the Right Test</h2>
<div class="cell">
<div id="tbl-test-choice" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-test-choice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Guide to Choosing the Correct Statistical Test (Two Groups)
</figcaption>
<div aria-describedby="tbl-test-choice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-bordered cell caption-top" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Outcome Data Type</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Study Design</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Statistical Test</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">SPSS Procedure</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Categorical (Nominal)</td>
<td style="text-align: left;">2 independent groups</td>
<td style="text-align: left; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">Chi-square test</td>
<td style="text-align: left;">Analyze -&gt; Descriptive Statistics -&gt; Crosstabs</td>
</tr>
<tr class="even">
<td style="text-align: left;">Continuous (normal)</td>
<td style="text-align: left;">2 independent groups</td>
<td style="text-align: left; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">Independent samples t-test</td>
<td style="text-align: left;">Analyze -&gt; Compare Means -&gt; Independent-Samples T Test</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Continuous (normal)</td>
<td style="text-align: left;">2 related (paired) groups</td>
<td style="text-align: left; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">Paired samples t-test</td>
<td style="text-align: left;">Analyze -&gt; Compare Means -&gt; Paired-Samples T Test</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ordinal or non-normal continuous</td>
<td style="text-align: left;">2 independent groups</td>
<td style="text-align: left; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">Mann-Whitney U test</td>
<td style="text-align: left;">Analyze -&gt; Nonparametric Tests -&gt; Legacy Dialogs -&gt; 2 Independent Samples</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ordinal or non-normal continuous</td>
<td style="text-align: left;">2 related (paired) groups</td>
<td style="text-align: left; font-weight: bold; color: rgba(44, 123, 182, 1) !important;">Wilcoxon signed-ranks test</td>
<td style="text-align: left;">Analyze -&gt; Nonparametric Tests -&gt; Legacy Dialogs -&gt; 2 Related Samples</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-test-flowchart" class="quarto-float quarto-figure quarto-figure-center" data-fig-align="center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-test-flowchart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="ch05_files/figure-revealjs/fig-test-flowchart-1.png" class="quarto-figure quarto-figure-center" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-test-flowchart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Decision flowchart for selecting the correct test (two-group comparisons)
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Ordinal Outcomes Always Go to a Rank Test</strong></p>
</div>
<div class="callout-content">
<p>An ordinal outcome — such as a <strong>pain score</strong>, a satisfaction rating or a stage of disease — is never analysed with a t-test, even if it is written as numbers. Use the Mann-Whitney U test (independent groups) or the Wilcoxon signed-ranks test (paired).</p>
</div>
</div>
</div>
</section>
<section id="key-takeaways" class="slide level2 scrollable">
<h2>Key Takeaways</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Chapter 5 Summary</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><p>Hypothesis testing uses sample data to decide between two competing claims: the <strong>null hypothesis (<span class="math inline">\(H_0\)</span>)</strong> and the <strong>alternative hypothesis (<span class="math inline">\(H_1\)</span>)</strong>.</p></li>
<li><p>The <strong>test statistic</strong> measures how far the data are from <span class="math inline">\(H_0\)</span>. By hand we compare it with a <strong>critical value</strong>; in SPSS we compare the <strong>p-value</strong> with <span class="math inline">\(\alpha\)</span>. Both give the same decision.</p></li>
<li><p>The <strong>p-value</strong> is the probability of the observed data (or more extreme) if <span class="math inline">\(H_0\)</span> is true. A p-value <span class="math inline">\(\leq \alpha\)</span> (usually 0.05) leads us to <strong>reject <span class="math inline">\(H_0\)</span></strong>.</p></li>
<li><p><strong>Type I error (α):</strong> rejecting a true <span class="math inline">\(H_0\)</span> (false positive). <strong>Type II error (β):</strong> failing to reject a false <span class="math inline">\(H_0\)</span> (false negative).</p></li>
<li><p><strong>Chi-square test:</strong> for association between two categorical (nominal) variables in independent groups. Read the Pearson row, or Fisher’s exact test if any expected count is below 5.</p></li>
<li><p><strong>Independent samples t-test:</strong> for comparing means of two independent groups with continuous, approximately normal data. Read <strong>Levene’s test</strong> first to choose the row.</p></li>
<li><p><strong>Paired samples t-test:</strong> for comparing means of two related measurements (before/after, or matched pairs) when the differences are approximately normal.</p></li>
<li><p><strong>Mann-Whitney U test:</strong> for comparing two independent groups when the outcome is ordinal or the normality assumption is not met.</p></li>
<li><p><strong>Wilcoxon signed-ranks test:</strong> for comparing two <strong>related</strong> measurements when the outcome is ordinal or the differences are not normally distributed. It is the non-parametric alternative to the paired t-test. For both rank tests, convert <span class="math inline">\(U\)</span> or <span class="math inline">\(W\)</span> to a <strong>Z-score</strong> and <strong>reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(|z| &gt; 1.96\)</span></strong> — the same Z-score that SPSS reports.</p></li>
<li><p>Always choose the test based on <strong>data type</strong> and <strong>study design</strong> — using the wrong test leads to invalid conclusions.</p></li>
</ol>
</div>
</div>
</div>
</section>
<section id="formula-summary" class="slide level2">
<h2>Formula Summary</h2>
<table class="table-striped caption-top">
<caption>Formulas in this chapter</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 50%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: left;">Formula</th>
<th style="text-align: left;">Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Decision with SPSS</td>
<td style="text-align: left;">Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(p \leq \alpha\)</span></td>
<td style="text-align: left;">Usually <span class="math inline">\(\alpha = 0.05\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Expected frequency</td>
<td style="text-align: left;"><span class="math inline">\(E = \dfrac{\text{Row total} \times \text{Column total}}{n}\)</span></td>
<td style="text-align: left;">All <span class="math inline">\(E \geq 5\)</span>, otherwise Fisher’s exact test</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chi-square</td>
<td style="text-align: left;"><span class="math inline">\(\chi^2 = \sum \dfrac{(O - E)^2}{E}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(df = (r-1)(c-1)\)</span>; reject if <span class="math inline">\(\chi^2 &gt; \chi^2_{0.95,\,df}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Pooled SD</td>
<td style="text-align: left;"><span class="math inline">\(s_p = \sqrt{\dfrac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1 + n_2 - 2}}\)</span></td>
<td style="text-align: left;">Equal variances (Levene Sig. <span class="math inline">\(&gt; 0.05\)</span>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Independent t</td>
<td style="text-align: left;"><span class="math inline">\(t = \dfrac{\bar{x}_1 - \bar{x}_2}{s_p \sqrt{\frac{1}{n_1} + \frac{1}{n_2}}}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(df = n_1 + n_2 - 2\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Welch SE</td>
<td style="text-align: left;"><span class="math inline">\(SE = \sqrt{\dfrac{s_1^2}{n_1} + \dfrac{s_2^2}{n_2}}\)</span></td>
<td style="text-align: left;">Unequal variances; df from SPSS</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Paired t</td>
<td style="text-align: left;"><span class="math inline">\(t = \dfrac{\bar{d}}{s_d / \sqrt{n}}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(d_i = x_{1i} - x_{2i}\)</span>; <span class="math inline">\(df = n - 1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Decision for t</td>
<td style="text-align: left;">Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(|t| &gt; t_{0.975,\,df}\)</span></td>
<td style="text-align: left;">Two-tailed, <span class="math inline">\(\alpha = 0.05\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mann-Whitney U</td>
<td style="text-align: left;"><span class="math inline">\(U_1 = n_1 n_2 + \dfrac{n_1(n_1+1)}{2} - W_1\)</span>, <span class="math inline">\(U = \min(U_1, U_2)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(W_1\)</span> = rank sum of group 1</td>
</tr>
<tr class="even">
<td style="text-align: left;">U to Z</td>
<td style="text-align: left;"><span class="math inline">\(z = \dfrac{U - n_1 n_2 / 2}{\sqrt{n_1 n_2 (n_1 + n_2 + 1)/12}}\)</span></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wilcoxon W</td>
<td style="text-align: left;"><span class="math inline">\(W = \min(W^{+}, W^{-})\)</span></td>
<td style="text-align: left;">Drop zero differences first</td>
</tr>
<tr class="even">
<td style="text-align: left;">W to Z</td>
<td style="text-align: left;"><span class="math inline">\(z = \dfrac{W - n(n+1)/4}{\sqrt{n(n+1)(2n+1)/24}}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(n\)</span> = number of non-zero pairs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Decision for U and W</td>
<td style="text-align: left;">Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(|z| &gt; 1.96\)</span></td>
<td style="text-align: left;">Same Z as SPSS (up to ties)</td>
</tr>
</tbody>
</table>
</section>
<section id="exercises" class="slide level2">
<h2>Exercises</h2>
<div class="callout callout-caution no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercise 1 — Chi-Square Test</strong></p>
</div>
<div class="callout-content">
<p>A researcher investigates whether <strong>physical activity level</strong> is associated with <strong>diabetes status</strong> in 300 adults:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Diabetes</th>
<th style="text-align: center;">No Diabetes</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Active</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">132</td>
<td style="text-align: center;">150</td>
</tr>
<tr class="even">
<td>Inactive</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">108</td>
<td style="text-align: center;">150</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;"><strong>60</strong></td>
<td style="text-align: center;"><strong>240</strong></td>
<td style="text-align: center;"><strong>300</strong></td>
</tr>
</tbody>
</table>
<p><strong>(a)</strong> State <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_1\)</span>.</p>
<p><strong>(b)</strong> Calculate all expected frequencies and verify the chi-square condition is met.</p>
<p><strong>(c)</strong> Calculate the chi-square test statistic.</p>
<p><strong>(d)</strong> At <span class="math inline">\(\alpha = 0.05\)</span>, what is your conclusion?</p>
<p><strong>(e)</strong> In plain language, what does your result mean?</p>
</div>
</div>
</div>
<div class="callout callout-caution no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercise 2 — Independent Samples t-Test</strong></p>
</div>
<div class="callout-content">
<p>A study compares the <strong>mean hemoglobin levels (g/dL)</strong> between male and female patients:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: center;">n</th>
<th style="text-align: center;"><span class="math inline">\(\bar{x}\)</span></th>
<th style="text-align: center;">s</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Male</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">14.8</td>
<td style="text-align: center;">1.6</td>
</tr>
<tr class="even">
<td>Female</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">12.9</td>
<td style="text-align: center;">1.4</td>
</tr>
</tbody>
</table>
<p>In SPSS, Levene’s test for these data gives Sig. = 0.41.</p>
<p><strong>(a)</strong> State <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_1\)</span> (two-tailed).</p>
<p><strong>(b)</strong> Based on Levene’s test, should you use the “Equal variances assumed” or the “Equal variances not assumed” version? Why?</p>
<p><strong>(c)</strong> Calculate the pooled standard error.</p>
<p><strong>(d)</strong> Calculate the t test statistic.</p>
<p><strong>(e)</strong> At <span class="math inline">\(\alpha = 0.05\)</span> with appropriate df, state your conclusion.</p>
</div>
</div>
</div>
<div class="callout callout-caution no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercise 3 — Paired Samples t-Test</strong></p>
</div>
<div class="callout-content">
<p>A diabetes clinic measures the <strong>capillary blood glucose (mg/dL)</strong> of 8 patients with type 2 diabetes <strong>before</strong> and <strong>2 hours after</strong> a structured 30-minute walking session:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Patient</th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">5</th>
<th style="text-align: center;">6</th>
<th style="text-align: center;">7</th>
<th style="text-align: center;">8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Before</td>
<td style="text-align: center;">182</td>
<td style="text-align: center;">165</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">148</td>
<td style="text-align: center;">195</td>
<td style="text-align: center;">172</td>
<td style="text-align: center;">160</td>
<td style="text-align: center;">188</td>
</tr>
<tr class="even">
<td>After</td>
<td style="text-align: center;">160</td>
<td style="text-align: center;">150</td>
<td style="text-align: center;">182</td>
<td style="text-align: center;">141</td>
<td style="text-align: center;">170</td>
<td style="text-align: center;">158</td>
<td style="text-align: center;">152</td>
<td style="text-align: center;">165</td>
</tr>
</tbody>
</table>
<p>Assume the differences are approximately normally distributed.</p>
<p><strong>(a)</strong> Calculate the difference <span class="math inline">\(d_i\)</span> = Before − After for each patient.</p>
<p><strong>(b)</strong> Calculate <span class="math inline">\(\bar{d}\)</span> and <span class="math inline">\(s_d\)</span>.</p>
<p><strong>(c)</strong> Calculate the paired t statistic.</p>
<p><strong>(d)</strong> At <span class="math inline">\(\alpha = 0.05\)</span>, did blood glucose change significantly after the walking session? In which direction? State your conclusion clearly.</p>
<p><strong>(e)</strong> Which variable would you check for normality in SPSS before using this test, and which SPSS procedure would you use?</p>
</div>
</div>
</div>
<div class="callout callout-caution no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercise 4 — Mann-Whitney U Test</strong></p>
</div>
<div class="callout-content">
<p>A physiotherapy team records the <strong>time to first walk after knee surgery (hours)</strong>, which is strongly right-skewed, for two independent groups of patients:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Group</th>
<th>Time to first walk (hours)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Early mobilisation programme</td>
<td>12, 18, 9, 30, 15</td>
</tr>
<tr class="even">
<td>Usual care</td>
<td>22, 35, 28, 40, 26, 48</td>
</tr>
</tbody>
</table>
<p><strong>(a)</strong> Explain why the Mann-Whitney U test is used rather than the independent samples t-test.</p>
<p><strong>(b)</strong> Rank all 11 values together and find the rank sums <span class="math inline">\(W_1\)</span> and <span class="math inline">\(W_2\)</span>.</p>
<p><strong>(c)</strong> Calculate <span class="math inline">\(U_1\)</span>, <span class="math inline">\(U_2\)</span> and <span class="math inline">\(U\)</span>.</p>
<p><strong>(d)</strong> Convert <span class="math inline">\(U\)</span> to a Z-score and state your conclusion at <span class="math inline">\(\alpha = 0.05\)</span>. Use the Z-table to find the approximate p-value.</p>
</div>
</div>
</div>
<div class="callout callout-caution no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercise 5 — Wilcoxon Signed-Ranks Test</strong></p>
</div>
<div class="callout-content">
<p>An anxiety score (0–20, <strong>ordinal</strong>) was recorded for 9 patients before and after a pre-operative education session:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Patient</th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">5</th>
<th style="text-align: center;">6</th>
<th style="text-align: center;">7</th>
<th style="text-align: center;">8</th>
<th style="text-align: center;">9</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Before</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">17</td>
</tr>
<tr class="even">
<td>After</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">7</td>
</tr>
</tbody>
</table>
<p><strong>(a)</strong> Calculate <span class="math inline">\(d\)</span> = Before − After for each patient.</p>
<p><strong>(b)</strong> Rank <span class="math inline">\(|d|\)</span> (use average ranks for ties) and find <span class="math inline">\(W^{+}\)</span>, <span class="math inline">\(W^{-}\)</span> and <span class="math inline">\(W\)</span>.</p>
<p><strong>(c)</strong> Convert <span class="math inline">\(W\)</span> to a Z-score and state your conclusion at <span class="math inline">\(\alpha = 0.05\)</span>. Did anxiety go up or down?</p>
</div>
</div>
</div>
<div class="callout callout-caution no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exercise 6 — Choosing the Right Test</strong></p>
</div>
<div class="callout-content">
<p>For each scenario below, state which statistical test is most appropriate and briefly explain why:</p>
<p><strong>(a)</strong> Comparing the proportion of post-operative complications between patients who received standard care vs.&nbsp;enhanced recovery protocol.</p>
<p><strong>(b)</strong> Comparing patient satisfaction scores (rated: Poor / Fair / Good / Excellent) between two hospital wards.</p>
<p><strong>(c)</strong> Measuring the effect of a new diet on body weight by recording each participant’s weight before and after a 12-week program (the differences are approximately normal).</p>
<p><strong>(d)</strong> Comparing the mean length of hospital stay (days) between two age groups (under 60 vs.&nbsp;60 and over), where length-of-stay data is strongly right-skewed.</p>
<p><strong>(e)</strong> Comparing pain scores (0–10, ordinal) recorded for the <strong>same</strong> patients before and 24 hours after starting a new analgesic.</p>
</div>
</div>
</div>
<p><em>End of Chapter 5</em></p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Coming Up Next</strong></p>
</div>
<div class="callout-content">
<p><strong>Chapter 6: Introduction to Statistical Modeling</strong> — We take our first steps beyond comparing two groups, exploring how one variable can be used to explain or predict another through <strong>linear regression</strong>.</p>
</div>
</div>
</div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="ch05_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="ch05_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="ch05_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="ch05_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="ch05_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="ch05_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="ch05_files/libs/revealjs/plugin/reveal-pointer/pointer.js"></script>
  <script src="ch05_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="ch05_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="ch05_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="ch05_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="ch05_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true,"theme":"whiteboard","boardmarkerWidth":4},
'pointer': {"key":"q","color":"red","pointerSize":18,"alwaysVisible":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, RevealPointer, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script>
    // Adds a clickable laser-pointer button next to the chalkboard buttons.
    // It sends the same "q" key press that the pointer plugin listens for.
    (function () {
      function pressQ() {
        var ev = new KeyboardEvent("keydown", { key: "q", bubbles: true });
        Object.defineProperty(ev, "keyCode", { get: function () { return 81; } });
        Object.defineProperty(ev, "which",   { get: function () { return 81; } });
        document.dispatchEvent(ev);
      }
      function addButton() {
        var bar = document.querySelector(".slide-chalkboard-buttons");
        if (!bar || document.querySelector(".slide-pointer-button")) return;
        var btn = document.createElement("span");
        btn.className = "slide-pointer-button";
        btn.title = "Toggle laser pointer (q)";
        btn.innerHTML = '<span class="dot"></span>';
        btn.addEventListener("click", function (e) {
          e.preventDefault(); e.stopPropagation(); pressQ();
        });
        bar.appendChild(btn);
      }
      // keep the button's look in step with the pointer, however it was toggled
      document.addEventListener("keydown", function (e) {
        if (e.keyCode === 81 && !e.ctrlKey && !e.metaKey && !e.altKey) {
          var b = document.querySelector(".slide-pointer-button");
          if (b) b.classList.toggle("active");
        }
      });
      if (window.Reveal && Reveal.isReady && Reveal.isReady()) addButton();
      else if (window.Reveal) Reveal.on("ready", addButton);
      window.addEventListener("load", addButton);
    })();
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>